In [1]:
import pandas as pd
import numpy as np  
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
final_df=pd.read_csv('D:\CA_content\Python\Final_Project\Final_Cleaned_Dataset_with_sorting.csv')

<>:1: SyntaxWarning: invalid escape sequence '\C'
<>:1: SyntaxWarning: invalid escape sequence '\C'
C:\Users\asus\AppData\Local\Temp\ipykernel_21328\692784765.py:1: SyntaxWarning: invalid escape sequence '\C'
  final_df=pd.read_csv('D:\CA_content\Python\Final_Project\Final_Cleaned_Dataset_with_sorting.csv')

In [3]:
# Sirf wo rows rakhein jinki price 0 se zyada hai
final_df = final_df[final_df['price'] > 0]

# Verify karein
print(f"Rows after removing zero prices: {final_df.shape[0]}")

Rows after removing zero prices: 6708805

In [4]:
final_df.info()

<class 'pandas.DataFrame'>
Index: 6708805 entries, 0 to 6727450
Data columns (total 12 columns):
 #   Column                Dtype
---  ------                -----
 0   event_time            str
 1   event_type            str
 2   product_id            int64
 3   category_id           int64
 4   category_code         str
 5   brand                 str
 6   price                 float64
 7   user_id               int64
 8   user_session          str
 9   category_code_filled  str
 10  brand_filled          str
 11  hour                  int64
dtypes: float64(1), int64(4), str(7)
memory usage: 665.4 MB

In [36]:
final_df['event_time'] = pd.to_datetime(final_df['event_time'])
seq_df = final_df.sort_values(by=['user_session', 'event_time']).copy()

In [20]:
seq_df.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session,category_code_filled,brand_filled,hour
0,2019-11-02 13:29:04+00:00,view,12300059,2053013556311359947,construction.tools.drill,bosch,69.17,513196170,00000510-834a-498a-9bed-561a90c5125e,construction.tools.drill,bosch,13
1,2019-11-01 19:06:53+00:00,view,1002544,2053013555631882655,electronics.smartphone,apple,458.25,514001239,000009c4-a1dd-4764-87d9-24f3d7e43c4f,electronics.smartphone,apple,19
2,2019-11-01 19:07:11+00:00,view,1002544,2053013555631882655,electronics.smartphone,apple,458.25,514001239,000009c4-a1dd-4764-87d9-24f3d7e43c4f,electronics.smartphone,apple,19
3,2019-11-01 19:08:13+00:00,view,1004659,2053013555631882655,electronics.smartphone,samsung,716.76,514001239,000009c4-a1dd-4764-87d9-24f3d7e43c4f,electronics.smartphone,samsung,19
4,2019-11-01 19:09:55+00:00,view,1004659,2053013555631882655,electronics.smartphone,samsung,716.76,514001239,000009c4-a1dd-4764-87d9-24f3d7e43c4f,electronics.smartphone,samsung,19

In [7]:
session_targets = seq_df.groupby('user_session')['event_type'].apply(
    lambda events: 1 if 'purchase' in events.values else 0
).to_dict()

In [8]:
session_targets

{'00000510-834a-498a-9bed-561a90c5125e': 0,
 '000009c4-a1dd-4764-87d9-24f3d7e43c4f': 0,
 '0000189b-6d2d-45bc-a65c-3a9d94e330a4': 0,
 '000029a6-1986-4a71-8139-53669c1adaba': 0,
 '00003dca-5a5a-4af2-86ef-9851ceb02a2b': 0,
 '00004022-c43d-4223-b5ad-da2b0e59b84f': 0,
 '000077fb-5f32-4a86-a179-2bbf8c34e9d8': 0,
 '00007d1a-aa00-4a01-b03c-879973251c53': 0,
 '0000a101-4e26-488a-85e9-f666baec0fc5': 0,
 '0000ae8f-570d-4a89-9690-6f22050b8175': 0,
 '0000be71-fe05-4b44-af8e-e8de041095d2': 0,
 '0000d24a-8726-4415-b256-4bc0e7b8c14f': 0,
 '0000d442-3df2-4942-81e3-3ff3d5385701': 0,
 '0000d540-b6d7-4ad0-845a-2055cb5c6bd8': 0,
 '0000e7f9-2292-4e7b-8844-0faa14df9a02': 0,
 '0001170e-5cd1-49be-a351-a4ab375b8a9a': 0,
 '00011aca-0f0b-484c-b944-b36edb777492': 0,
 '00013570-3379-43cf-94f0-454a55834f55': 0,
 '0001367d-b671-412b-af55-b831628a6f54': 0,
 '00017baf-3bda-4bc5-945c-63c08676f288': 0,
 '00017f39-e983-4655-9db2-ae3bea7f0071': 0,
 '000199a3-437c-4ae8-b26b-01e0f34c1418': 1,
 '00019c1f-02da-48ea-85f9-a8b769cd110b': 0,
 '0001a1b4-7adf-4c7a-9230-fdc1f1ae4e7c': 1,
 '0001b18c-ed04-46b4-8d51-e567aac896c5': 0,
 '0001b609-dbb0-4c1e-a036-2da4048f5760': 0,
 '0001c990-bf26-46ba-9723-276014ad799d': 0,
 '0001ca7b-f310-4547-9c1c-25ae985d67ab': 0,
 '0001d184-5468-48ed-9921-558cb1d704b8': 0,
 '0001d965-19b9-4ffc-a211-b71a73322926': 0,
 '0001dfeb-436c-4f43-b7bd-0575fee6061f': 0,
 '0001e60a-af51-40fb-a0d6-27e84223b0ad': 0,
 '0001ef1e-22bc-47d1-b429-4479b29adfd2': 0,
 '0001efdd-9649-44cc-9911-ca001c9844d5': 0,
 '0001ff3c-df26-4a66-a3d9-b9955a780003': 0,
 '000204ef-9c82-421b-a5b1-b982c31b2299': 0,
 '00020ffd-a607-4570-9da2-65ee82680a54': 0,
 '000210bc-245f-47f6-a58f-e0a6586496d5': 0,
 '000211a5-3f6b-4563-ac7e-da49604ca683': 0,
 '00021c98-687c-4fbe-b432-92929ab48eb1': 0,
 '00022399-61de-424a-8911-9b6b049a4a32': 0,
 '00022d99-0df7-426c-a93e-71a62734677f': 0,
 '00025740-6e46-4e58-a51a-3d0093141d88': 0,
 '000259d7-f50b-440f-8605-78e660096afc': 0,
 '00025fc8-8ecd-4c34-a880-f3d7f73d553f': 0,
 '00026a83-dea6-4efd-93e8-ab3e52e7673a': 0,
 '00026fdb-9b76-4871-b565-898ef9d30520': 0,
 '00028c1f-f789-44be-a509-154d0f93ad74': 0,
 '0002a8a3-21eb-41af-9d6e-6de129706c8f': 0,
 '0002c06f-a314-4969-bf5d-d3094539288a': 0,
 '0002c67e-91c9-44d4-8fed-ee8298231db0': 0,
 '0002c976-7202-4b13-b335-0fe3af358c55': 0,
 '0002d13f-d666-45f1-92c2-a44581e33525': 0,
 '0002d70e-7a99-4601-a9ea-61539fb4c883': 0,
 '0002e288-569b-4642-8a82-b183ee537259': 1,
 '00030ff3-dc6b-48b9-be20-025715e70d67': 0,
 '0003277d-571a-4ad6-85b3-9d92d7e46ae0': 0,
 '00033d58-4d4e-424d-8723-24700639b0f7': 0,
 '00034bfd-f981-4997-b61a-4f69803259b7': 0,
 '00034df0-0894-4f9a-85ec-731dbc7d620d': 0,
 '00035bd6-5e36-4dec-9f68-6161eb4e7917': 0,
 '00035f1a-f4f4-4170-8207-6406ec0259d7': 1,
 '00035feb-7620-410c-984b-b7d5a5b4fc93': 0,
 '0003799e-9f33-462c-a46e-b23643fb3741': 0,
 '000390da-1133-4577-9060-1e671acc1f8c': 0,
 '000396ce-ac40-49b2-bce6-be288d13d251': 0,
 '0003bb64-7420-4874-8ebc-d0a5e10eb67a': 0,
 '0003bf61-bada-458a-98a0-40f185b00322': 0,
 '0003c40f-13f7-411e-82cf-8633f7c0c127': 0,
 '0003cd86-09b2-4b93-8910-8509023bfbac': 0,
 '0003d2b1-c6c5-4963-a943-2b1d378c2b75': 0,
 '0003d309-361e-4962-bd6f-6528bdde9171': 0,
 '0003dbac-f398-420d-bba9-71450a108f50': 0,
 '0003de99-f459-415c-ab06-6ca8ce44c58d': 0,
 '0003e038-48fe-46f0-8343-fc4d721b109b': 0,
 '0003ea35-72ae-4c29-99b9-d85b85868b52': 0,
 '0003ef27-6d3b-4a6b-a8f8-d75285305ff4': 0,
 '0003fbe5-8a6a-4a56-b925-eaa48a7c7bc4': 0,
 '000441b1-66c6-49f7-9c4d-2f236a4c02c1': 0,
 '00046b13-1825-44c8-b136-9831626905c7': 0,
 '00046db5-9cac-4f48-85f7-cf0f26b538e0': 0,
 '00048083-ce0e-4462-b6c5-1b61dcbe43a1': 1,
 '00048a82-fc4c-4f99-b927-53d495b32eb8': 0,
 '000490bb-9d08-43ff-8ff3-9332ed4fa00f': 0,
 '0004947d-f145-468c-8f8d-84a5f1d76187': 0,
 '0004a485-933c-43fa-8c24-708204724d4f': 0,
 '0004a582-9137-4a9b-9695-b743eaea850f': 1,
 '0004a69b-0736-4717-94ab-61540df5f26b': 0,
 '0004b2ca-e866-460c-8248-02b1602da1c4': 0,
 '0004b526-db41-4c5c-8464-b06b602bc9cf': 0,
 '0004b77e-8f3a-45a5-b69c-80983d176d6c': 0,
 '0004bf4c-8fd4-4309-b5c4-b3f2ec348e11': 0,
 '0004df88-ee8b-4ab9-9804-45f05add05f8': 0,
 '00051140-2252-48ce-8589-b5f019a8015a': 0,
 '000521d9-15fb-4166-825d-89fcaa887452': 0,
 '000530fa-854b-4343-920a-07e7c2f57f4f': 0,
 '00053573-4a16-45fe-8353-916a6beb9f68': 0,
 '00053694-56b1-4ca4-b682-0b52e03bfec4': 0,
 '00053722-9cf0-4053-b91b-c1c699bc5689': 0,
 '00053c28-d182-42f2-b1b5-f525a622d96e': 0,
 '000559c0-fec5-42f7-b1e3-9f5a4d04e460': 1,
 '00057cf3-246f-4843-bae1-d16a1ea32183': 0,
 '000581af-da49-44a0-b2a4-a0e84382951f': 0,
 '000583d9-a9c5-40eb-9b3e-2e6d95515042': 0,
 '00058e0a-2d65-1283-f1a3-d9aefa6fcada': 0,
 '00058f8b-30e4-401c-ae00-eec9ceddfe40': 0,
 '0005a7d1-7eac-4226-9535-189eb3a7de56': 0,
 '0005cbef-7043-4832-a483-7d109008ef1a': 0,
 '0005d58b-ef5c-48d5-a9e1-822280826293': 0,
 '0005e9c7-aa37-476c-8f3c-69e45c714abb': 0,
 '0005ebb0-ed47-4eae-a46c-4d429dfd276c': 0,
 '0005ee26-e436-dace-11be-3b8fe6f786f2': 0,
 '0005f025-d675-4344-897c-68897a6ea601': 1,
 '0005f2a3-c212-46b0-9713-0afe85628f2a': 0,
 '0005f371-924a-4a53-b0f7-2775ad0e6bf7': 0,
 '0005f3e5-ef5c-4d84-b201-a1ce2a813b45': 0,
 '0005f6d4-7f9e-434a-8edf-a715009b2a7f': 0,
 '000607ca-4dd7-4c0c-ab22-2c099a6a027d': 0,
 '0006134d-cac6-4a9e-a982-e8d3c1ba22cf': 0,
 '000614f6-9f94-b420-e159-40780d323fc7': 0,
 '00061e84-3908-430b-9453-b185aab2d3b5': 0,
 '00064be1-294e-4454-9c31-642fd5b6ce89': 0,
 '00065068-67d1-4883-8c5c-017c496c597c': 0,
 '000665d4-4472-4e19-9517-a45feae32f5b': 1,
 '000667c6-b580-48c6-b650-a07969b4e15f': 0,
 '00067110-7e9a-4506-aa88-aaa933dc880b': 0,
 '00067f60-9efc-4985-ae73-04397d2316d2': 0,
 '00068bad-fc40-448f-9282-8c56e1921856': 0,
 '0006aafb-1b95-4383-8e7a-6c99bb757e97': 0,
 '0006afcd-fa4c-4d1d-a9ab-571cfdcfb79f': 0,
 '0006b22b-efa7-40a2-867f-7818e6eca5af': 0,
 '0006bf4b-51c6-4649-a325-84482543fec1': 0,
 '0006d193-da98-4e6f-869a-b6060ae10339': 0,
 '0006d3d1-6e80-4876-ae65-d073551701c1': 0,
 '0006dbff-4c32-413a-a52d-f4c8269b1d79': 1,
 '0006f116-ba9a-4e9a-a92f-f71f64feed44': 0,
 '0006f937-0ed8-4c37-a160-e66162fe19f4': 0,
 '00070beb-de17-4f65-866a-69eb1a455166': 0,
 '0007111d-0526-4561-b47b-fc5e16961e79': 0,
 '000712b3-ca94-421f-b126-fbff68dc4776': 1,
 '000712c0-4d7e-4dc5-9932-2fa469f5fc60': 0,
 '00071aac-4f57-442b-a52b-f8f7cedf2421': 0,
 '00071b49-7f92-4e47-8384-095e64d78c10': 0,
 '00072231-a36d-440d-bc81-47329c6b047c': 0,
 '000723ea-3fe8-4b89-bb0f-5c4cc1d43060': 0,
 '00072b2c-cf71-4f98-8160-416234a749ed': 0,
 '00073120-f5b4-479d-b583-f72ec32c81a6': 0,
 '00074e23-b9c1-483b-8ffd-6c0914a10973': 0,
 '00075c4c-e380-44e5-a093-bb7166d99c84': 0,
 '00077187-2140-4a0e-a806-3d20b8d533dc': 1,
 '0007758a-ce73-47f9-a61c-f9f44f40d252': 0,
 '00077cc5-e1f2-4cdf-b596-e163b59a06bc': 0,
 '000783b7-d621-48c3-8e4f-96baf0b312bc': 0,
 '000789af-458b-47b9-9df9-c0f1ab442681': 0,
 '00078b77-972a-4afa-abca-5bd6563e60c8': 0,
 '00078c86-e30d-4b07-b53c-becc305e0862': 0,
 '0007a10a-31e7-4bd1-b5ff-f06fe5dc9029': 0,
 '0007b5b3-0bcb-4df0-993b-39d12a0e58dd': 0,
 '0007c63b-16f1-404c-b6bc-f123804485d4': 0,
 '0007cc05-825d-4137-85b2-c8de23bd98f2': 0,
 '0007d9fb-853c-4b52-bae0-1461ded022e2': 0,
 '0007e937-551d-42df-a4e6-f792c2b6a1de': 0,
 '0007f238-2612-dfbb-08b7-53974443de63': 0,
 '0007f945-0838-4288-a819-56bc96ac09a4': 0,
 '00080171-595d-469b-8573-d064ad27cd12': 0,
 '000810bd-f0e9-4b78-90cd-b02c7463d000': 0,
 '00081da4-ef57-480a-a083-914f0d8020a5': 0,
 '00082674-12de-47d0-8fe3-efd70ddde8c2': 0,
 '00082ce7-f968-402d-b899-90bd0b125fd2': 0,
 '00082eb0-5896-4ad3-b418-c9606deeebf6': 0,
 '00083dbb-2064-4d96-aa1f-140026e2d67b': 0,
 '00087a56-7c2f-4268-9e7a-3d1dbc3b7bb2': 0,
 '00089730-9dd0-4768-8910-efc2abb87d90': 0,
 '00089e52-feab-4211-b269-c5a3eb27c11f': 0,
 '0008b535-1132-40c0-843e-a0d78a659c4e': 0,
 '0008fa53-31d6-4749-b943-468be501b8e2': 0,
 '00090eab-c1f8-4741-96c4-828efff24e96': 0,
 '00091202-8abc-440c-905f-bd75fec7b840': 0,
 '000917c6-5f55-41ce-a56f-d98750e4c484': 0,
 '0009189f-8895-42fa-ad59-a483a52555c2': 0,
 '000920d3-efa9-4a05-9f16-435ec9799bd7': 0,
 '00092365-8f79-48de-8a0d-81620eb604ca': 0,
 '0009263c-3964-474e-8aa5-8af1e6eab791': 0,
 '00093a31-ac7c-4449-9dfc-5d67f7157ce6': 0,
 '0009478b-10cb-4abf-b36f-cf568c11303b': 0,
 '000954b4-c838-47cb-adc7-d049ec17e524': 0,
 '000959d9-0696-46a3-b968-c2d5d46107e1': 0,
 '0009601b-285e-4620-9bc8-6c0bc66e63fc': 0,
 '0009637a-5d57-489d-b88a-227bb4944193': 0,
 '000966a4-4fd4-4013-b094-d13d1d70f39a': 0,
 '00096a4c-18ae-4b9d-9b06-85e3e166addd': 0,
 '00097ba8-be90-47f9-998f-33d744dd5b22': 0,
 '00098838-00ec-48f6-b260-87b26aa0bc8f': 0,
 '000990d8-3962-4e52-9c88-8c011e888126': 1,
 '000991c4-6bb2-49f4-bb92-3057a9c247d5': 0,
 '0009a4b1-b7f6-47ec-9189-9040c7c567e7': 0,
 '0009b163-bc93-45d8-9fb9-49ae3a4ad9c0': 0,
 '0009b704-1186-4217-b7a8-08608fb11141': 0,
 '0009b84e-a910-4717-a0bd-44a72c5f5bf4': 0,
 '0009c064-4cbb-40d7-9b68-9a82c479e666': 0,
 '0009c4df-7e73-4c9b-a00d-5dcb2c5cf055': 0,
 '0009c74a-de57-4fb5-ba2d-fdda6d785d48': 0,
 '0009d81f-14fb-4be0-b569-f7b50d75a458': 0,
 '0009d83a-4fd6-4ddf-8479-482e1b3dcd51': 0,
 '0009fdb1-33ae-4740-b88b-27cfac163f44': 0,
 '000a1d10-f23a-456b-98c5-e33b3cfd6ce1': 0,
 '000a2c7e-5c12-4ed8-9077-0708070cd341': 0,
 '000a3a08-2ab9-4d6f-a04b-ec9f27540937': 0,
 '000a41ec-4af1-4ddf-9efd-342219ee3fb2': 0,
 '000a4333-d44a-45ac-9658-31cad0fb651d': 0,
 '000a4e00-153d-4742-9158-dfb545dd7bf8': 0,
 '000a58f1-b0e9-47d9-9921-a8f51ddf7e49': 0,
 '000a64df-8c7d-4d39-8fd5-ebc0176f207d': 0,
 '000a6604-997b-4ff6-b9ab-9ad422fa65fa': 0,
 '000a78b2-b9be-471d-a7d5-ee4a409cb907': 0,
 '000a858d-aeaa-4745-812d-79d7f6936cd7': 0,
 '000a8afd-7e76-471c-b651-95652e296eb4': 0,
 '000a8f80-361d-4b35-86fd-74add8575fcf': 0,
 '000a8ff9-c7cd-4ab9-8ac0-117ae80ec2fb': 0,
 '000a9e2f-894f-4b20-83a5-8c5b5ce480d6': 0,
 '000aaf10-e279-4167-b44e-dac27821fbe6': 0,
 '000ab2f7-60c1-4235-b810-1e31c7a1a136': 0,
 '000ab6b7-cad7-4dac-b2cf-0a449bb2178f': 0,
 '000abf18-6705-4664-a0c8-1514b04d8651': 0,
 '000acc60-778c-4363-a4af-9ea5a1abe5e2': 0,
 '000aea45-ab51-4fd4-a0be-566577ea85af': 0,
 '000af92a-8985-45a8-9c9a-73b0e8a687e9': 0,
 '000afa4f-9bc3-4fd0-a054-79055bd53758': 0,
 '000b0306-ddaa-468c-b84b-e887b2d07d7c': 0,
 '000b0618-3d19-4872-b6c1-5a327b7814a8': 0,
 '000b36dd-0c43-4d28-90e0-9c277296462b': 0,
 '000b4294-fd83-44a4-b446-9c3d785c348d': 0,
 '000b4ce9-4d92-46ec-85c2-2ed9b266e5ce': 0,
 '000b52ba-d4d9-4d34-809d-95ba1a10e713': 0,
 '000b5414-4296-423e-ae47-2f4283cbe386': 0,
 '000b7623-c834-428b-b547-e00eec9ad766': 0,
 '000b795f-e184-46be-bf12-c07cd575a46b': 0,
 '000b8010-49cf-479b-a25d-2ac4fe66f3b4': 0,
 '000b89d9-5ca8-4144-a1c2-0cff38915a28': 1,
 '000b9fe3-20b6-4483-a75a-9675d215654b': 0,
 '000bb1fd-8515-4a7c-b987-4e318c48f260': 0,
 '000bbb2f-1dbd-4197-ba26-07a1c8fc9299': 0,
 '000bbca3-45c9-419d-aae1-f189614385c2': 1,
 '000bc879-ab51-4c2e-935a-5780bbd84417': 0,
 '000bcd70-7620-4274-8d34-a9997e0da501': 0,
 '000bddd2-c3e2-4fab-898e-24c48dd323c6': 0,
 '000be7d0-fa14-4dab-9526-cb99dbd8a705': 0,
 '000beb0b-443c-4e0c-8478-063698783272': 0,
 '000c0b7d-8b1e-4962-a732-1e7476a69c67': 0,
 '000c117e-6e5b-4159-abae-a259fedbba28': 1,
 '000c1ad5-c46f-4293-b979-23429bdbfec1': 0,
 '000c2d87-e5bd-4b07-8037-00106c3a0a06': 0,
 '000c6751-9464-4462-9d16-adec3c499ad9': 0,
 '000c6a37-e8f2-4710-bfd3-afcbd8ce4372': 0,
 '000cb116-2aec-4238-a38b-3caa157d7ff1': 0,
 '000cb669-b158-4fee-b062-a6f5d9c5680f': 0,
 '000cc516-6038-4b9d-aaf7-2cb5eff83ae7': 0,
 '000cc850-9d2b-4bfd-9dfb-68e61e396a72': 0,
 '000cd375-7d7c-4062-8ce4-e1f60c557caa': 0,
 '000cdb9d-5f9b-48df-b638-37be2a3e7434': 0,
 '000ce03f-756e-413d-9033-39b69937fdb4': 0,
 '000ce7de-1db2-4d63-8308-854c4e34d05b': 0,
 '000ceef5-afad-4a45-94fc-3d861eaae590': 0,
 '000cf5a8-b570-4287-bb77-8481894cc587': 0,
 '000d10e9-9de7-4f44-b863-6dc7eb0d4368': 1,
 '000d14c9-f88f-4f80-bc78-8646692936bc': 0,
 '000d33a0-a3ad-467e-b6c4-239e8576f814': 0,
 '000d3e53-b113-440d-b359-92aa745bc8c4': 0,
 '000d4944-e9f6-430f-ae5b-86e1649f8572': 1,
 '000d4caf-91b7-4a1f-b243-1e4c7665c276': 0,
 '000d642e-2438-4b12-8076-3b52a93fbf5b': 0,
 '000d6780-3f8a-44e7-8089-1d29fa52b1f3': 0,
 '000d6c47-60f0-4ca8-99dd-596b626b7fbc': 0,
 '000d8eed-8f45-48b8-8008-1bcdeda431f9': 0,
 '000da114-141d-4d90-a99b-de93b6d55295': 0,
 '000daa37-4221-46cd-8bb3-74446dd34780': 0,
 '000dcb84-409f-4d1e-a802-080492795062': 0,
 '000dcdff-fe37-4a46-ab68-795bee167891': 0,
 '000deada-c6aa-4346-a22a-247f97c806e3': 0,
 '000dec01-108f-4555-a7cf-dc32648794cf': 0,
 '000dfe11-8231-4446-b78e-db4efbf73a2c': 0,
 '000e1443-e950-4012-ad21-fecbe39d8085': 0,
 '000e1da4-b752-4b1e-ab02-ee160d0525e1': 0,
 '000e319d-012d-4e3e-91de-91cfa8fa767f': 0,
 '000e3585-63d6-40a7-92a0-6e929579b961': 0,
 '000e4909-f91d-4c6c-9435-db0782199be9': 0,
 '000e583a-1095-42bd-9637-822bc6247902': 0,
 '000e6343-3d07-4655-8f4b-939b5908f3d2': 0,
 '000e64f9-66b4-41f1-9382-6a88b456b644': 0,
 '000e72b8-e1be-42d2-858f-93fd657aa591': 0,
 '000e74b7-0b08-4ad0-b2e9-92ab4ff85f44': 0,
 '000e84f5-0903-47ff-b1a5-f0b2a472e0b5': 0,
 '000e876e-f9ee-4b18-beb2-835a1297953b': 0,
 '000e8d03-7458-4eda-bb7a-a0a5fce56e34': 0,
 '000e9511-2500-4945-8dba-9001aa397a73': 0,
 '000e9ece-4c73-4b90-810b-cb9b89e9417d': 0,
 '000edd92-9e9f-4a6d-9104-64b0f69765be': 0,
 '000ef36e-2cb3-4535-9dda-1d88713f74d4': 0,
 '000ef9db-60c6-47b2-9c9f-c2e008f9fded': 0,
 '000efc72-7b3d-43a8-bdf6-3d012316ab64': 0,
 '000f0ea6-eba5-4357-9907-177652430c78': 0,
 '000f1907-6d0d-4768-b319-e73b493438f1': 0,
 '000f27d2-fda1-4928-82b1-453d4621d710': 0,
 '000f3188-33bc-4a17-933b-c968a951f0cc': 0,
 '000f416b-461b-476a-ac1f-c72356651171': 0,
 '000f4ada-31df-4996-800b-cb1a1ca88fc5': 0,
 '000f4c3b-20c1-44e4-a9f3-8bc9169e6830': 0,
 '000f604c-3afa-4c97-8a69-b01503269392': 0,
 '000f6d9f-4dba-4dcf-87fe-14d996482dae': 0,
 '000f7609-d3d2-47be-9d61-c2e061999477': 0,
 '000f787c-130d-47e3-a0d5-b49a85c01902': 1,
 '000f8ead-7756-4dc5-8755-6ace25296fcd': 0,
 '000f8ec2-272b-4f51-a7a8-c8f9f708ab51': 0,
 '000f9286-0882-4239-a9ac-72e4b0041070': 0,
 '000fbc1d-3b97-40ac-b490-fb7325f875ba': 0,
 '000fbecd-b06a-46a3-9418-06e07b82f40b': 0,
 '000fc8c8-9172-4dbb-8f36-8d82a3879d30': 0,
 '000fcb7d-56d9-437f-b719-f422955289d7': 0,
 '000fcbec-75cb-4ff2-b21a-73ba7fab85c8': 0,
 '000fe0d0-741d-4567-8217-86a6ca8414c4': 0,
 '000fe244-ae47-4049-9537-a17723295bf7': 0,
 '000fe5b9-08fd-45a4-bc51-04ea468ad2b8': 0,
 '000ffb9e-317e-4c65-babf-5a5b9697016a': 0,
 '00101078-4e0f-4948-811b-b96fd234beb3': 0,
 '00101df0-40fd-4a3d-9ceb-d87ed410e805': 0,
 '00102213-7a74-4c70-be00-507c72a22ce8': 0,
 '0010288c-88aa-4df3-9c68-8e3576d68106': 0,
 '00102c62-2a53-481a-86fe-60e4a1e1dd39': 0,
 '001033d4-84f4-416e-b12b-8aafaffde45e': 0,
 '0010377f-71e2-9821-6cbd-3a7901e94c2e': 0,
 '00104447-c015-44bc-907b-87e46b7a7147': 0,
 '00104b8c-d7cb-4e46-9b3d-c7c03a181015': 0,
 '00104cf6-289e-4ee4-a60f-900601d6de2f': 0,
 '001054cc-ba25-46a3-b4b3-808b9e5960a0': 0,
 '001054db-8a3c-43c6-bc20-56740df69577': 0,
 '001060e5-1a05-42fe-ac6c-97fad8316e1e': 0,
 '00106b8c-068a-429b-b1eb-aa2339405783': 0,
 '00106d3b-5bf0-4fb5-947e-d8bc92358bd5': 0,
 '00108e98-51af-40b4-8045-dfd6515c86bd': 0,
 '0010947c-ad7c-477c-b11b-b2c6fc5a20d1': 0,
 '00109dd7-113b-4f84-99f7-25022b0105c7': 0,
 '0010a6ac-aa81-457e-bd60-5fb62a17c3de': 0,
 '0010af2b-787b-45e2-ae88-a633eb5b5f8a': 0,
 '0010bee4-8b8e-4a09-b7d5-0ba23c897c4a': 0,
 '0010c000-11be-414e-b2a0-6b813d95c23f': 0,
 '0010e495-4daf-42fc-9627-af46e3ce09a9': 0,
 '0010efff-703a-e132-d52f-60b96db41362': 0,
 '0010f121-03fc-4c16-bca2-7c3242b2e290': 0,
 '0010f3ab-7876-4469-9f0f-3b1253dcc3b9': 0,
 '00111315-fbd9-424f-bc2e-be416773b10d': 0,
 '0011202d-dfad-40a6-9c4c-0fc42558789f': 0,
 '00113283-9564-42f2-9327-77cf8bc30c9f': 0,
 '00113428-4cc1-4df4-99bd-d697f22e3abf': 0,
 '00113b0e-dd44-4dc5-b874-151f903dbfe4': 0,
 '00115427-5c9d-4d99-aa0c-702b95531022': 1,
 '00115aba-cd4f-4ebb-99d1-ef24c87fcb0f': 0,
 '00117281-88b3-416c-b5e3-c0fae1bf6f23': 0,
 '0011734b-a1ad-4057-a358-9e715ff96fd7': 0,
 '0011a36f-d950-4bd7-ae75-35143a7d5152': 0,
 '0011b271-24dd-4057-b138-24585c2e2006': 0,
 '0011b5d6-82ba-491b-a021-fa197733686d': 0,
 '0011b96f-99b2-4d10-bfe6-4e05b06111dc': 1,
 '0011c2b2-158b-4325-83a6-6c59a35d349e': 0,
 '0011c334-2aa8-4c32-ae20-cb5e77237b49': 0,
 '0011cf6b-c1c8-437f-8dc7-ed420bab469a': 1,
 '0011d5b0-2ffd-4fe7-8fcd-35eeed4db732': 0,
 '0011dbc5-2892-4d9f-a52a-a09f016699c1': 0,
 '0011dc04-61a5-4a57-8d4f-2687cfa7764e': 0,
 '0011f465-160f-429c-8f66-3639a37c49ba': 0,
 '0012000f-5802-461c-a7ef-a91329d05965': 1,
 '001202f6-51f5-4441-842a-c0c898ba8480': 0,
 '001207fa-c78d-4b50-9649-1c1f324a65d6': 0,
 '00120d1f-cc91-453f-b6b7-4ca36565d2a9': 0,
 '0012105a-8615-4a8b-915d-ea853f85f997': 0,
 '0012124d-788e-4e6a-9c1b-56e540001508': 1,
 '00124240-d762-4048-9ea0-cdf8764f6755': 0,
 '001246e5-efee-42ad-8745-5cb5775d7435': 0,
 '001248af-2899-41dc-ba39-b02d227f9473': 0,
 '00125f7c-70ff-42e3-a30e-2d12fabebe10': 0,
 '00127e4b-be69-4bc1-b1a2-4aa1d7ce841e': 0,
 '00128661-9009-451b-8bef-f8ecbf7b35b4': 0,
 '00128e51-ab0e-4dfa-9de4-686317b656f7': 0,
 '00128f3a-1af2-454a-8130-7768daf1b711': 0,
 '0012a7a7-8670-4474-8032-21e943f47090': 0,
 '0012af45-a61a-499b-bf48-06330c3ca417': 1,
 '0012b1ea-8a46-49b7-8bdf-f36e3d1cd050': 0,
 '0012b499-2ea9-4689-ac28-7783c8ccf3fa': 0,
 '0012c610-356d-41e9-8124-b24d630d9008': 0,
 '0012f931-ca45-441c-a632-9231aaed27e9': 0,
 '0012fe9d-9a6c-4a41-9e77-8b8dad44746b': 0,
 '00130207-0622-4a65-8e7c-ec8dff9df4f3': 0,
 '00132187-a431-4266-8eef-9590e748ff87': 0,
 '001349aa-03d7-c47d-9acc-15fad08112af': 0,
 '001355fc-a028-4e7d-a6e4-877951e004d4': 0,
 '00135ce5-2bde-448c-8018-b7571d0d73a2': 0,
 '001362f7-576b-446d-bafb-508fa395ecec': 0,
 '0013650a-05ff-4f25-a9ea-1fc915269b0a': 0,
 '00136b98-fea6-4429-b86a-01e034e03d26': 0,
 '0013865c-8fcf-423f-96c8-33afd0d97d9f': 0,
 '0013a0a0-0b4b-475c-a971-2a70827c0d09': 0,
 '0013a24a-8f60-419f-8771-62c50c45e95d': 0,
 '0013ad0d-eab7-4984-a0a5-95ee1742fd76': 0,
 '0013af22-dd96-41d6-8cc7-3d85c59f0f12': 0,
 '0013b329-91b1-47a1-988e-e056fc011379': 0,
 '0013b609-7f05-4dca-8c75-b04b57aa36ef': 0,
 '0013b927-130c-44c0-9cd3-cead6cb51889': 1,
 '0013bacb-dea6-445c-ba47-58148fcf66eb': 0,
 '0013bb9a-e46d-46cf-a627-1c44e2651a19': 0,
 '0013c23e-cc64-4d71-860c-ef772c1737af': 0,
 '0013c24f-99c4-416b-8dd5-77661dde0fb6': 0,
 '0013e26d-0f20-4022-9ce0-101615f89eee': 0,
 '0013e753-6100-4d08-a17c-56580d5d5d9b': 0,
 '0013ec54-1e0e-4122-84b0-4afc90827907': 0,
 '0013f3ae-efe9-40ae-8cf4-c13ea38cbd55': 0,
 '00140eb9-03f2-4fc7-9200-de6204a26b61': 0,
 '00141245-e17f-40f4-86cd-0e378ed73e23': 0,
 '001413e0-268b-41e8-a2f7-d71c73f446f0': 0,
 '00142a8a-af6d-46d0-bba9-19fb6a1f0a29': 0,
 '00142e76-51ff-4f21-8433-098396b99633': 0,
 '0014387b-1248-433e-af79-3818378816c9': 0,
 '00144273-40e3-4ddc-9798-0863f440dfc7': 0,
 '00144ba0-e8de-4c82-a86c-dbb6e5dd3656': 0,
 '001454a6-6e9e-4ba8-bfd0-16a605532b1d': 0,
 '001458a5-1587-4cc3-8df8-1f7ce70e410f': 0,
 '00145f87-37ff-4e80-929e-eceae85082e7': 0,
 '00147187-c26e-44a6-b679-65ae708ad814': 0,
 '001475f9-98b1-447b-a914-6aefab0fb39d': 0,
 '00147cc2-67c1-40b0-a9ff-5f7d99cf31a8': 0,
 '0014845b-7c65-4a22-b618-53778ac7ce7c': 0,
 '00149660-4d60-4d11-b8bc-3a06e5fed4c3': 0,
 '001498cc-c671-4692-9dc7-06d045d7c756': 1,
 '00149d64-b56b-409d-bb7f-ecaa7508ca1b': 0,
 '0014a687-8480-40e5-9542-5447c20edaf7': 0,
 '0014a74f-ee14-4e2a-89ca-71dbaeca32e6': 0,
 '0014b965-1914-41a9-854b-ac50b14fff22': 0,
 '0014d4ad-6c44-435a-804c-800f9e70d342': 0,
 '0014e5e3-16f0-49b3-8fbe-4b069ebd400f': 0,
 '0014f313-e572-404d-a4d1-de9f868c7e0c': 0,
 '0014f62b-d1f8-42b6-a726-c5f2137d736f': 0,
 '0014f698-6529-4c01-b833-37be04598d83': 0,
 '0014fbef-874e-44eb-bcde-fb13dad18e6f': 0,
 '00150d63-901b-4ba0-811e-40ab93046eac': 0,
 '00153170-c09f-4434-a1c8-c795f15a4b82': 0,
 '00153200-cec7-48a8-9889-c515deb6be06': 0,
 '00153fc3-feb1-4920-ab6c-b507aa2c2fa4': 0,
 '0015538f-6bfc-4317-ac7a-fc2262af4803': 0,
 '00155808-33fb-47cd-9cc9-0926ad18a6d6': 0,
 '00157025-22be-406c-8290-1cc95f900132': 0,
 '00157f35-aaba-4ff7-8a18-b97d3ed12327': 0,
 '00158378-8360-4b24-b407-88d54414e052': 0,
 '00158417-2d96-4a83-9dd6-9da61e1ec513': 0,
 '0015860d-7ca7-4b6e-b2fb-9ef3716e9249': 0,
 '001587ab-b257-4d37-836c-abcc2616e2e9': 0,
 '00158e16-c7e7-42f4-aaad-afd9b9ff4c60': 0,

In [ ]:
from sys import getsizeof
getsizeof(session_targets)//1024

30037

In [37]:
seq_df = seq_df[seq_df['event_type'] != 'purchase'].copy()

In [38]:
seq_df['is_view'] = (seq_df['event_type'] == 'view').astype(int)
seq_df['is_cart'] = (seq_df['event_type'] == 'cart').astype(int)

In [23]:
seq_df.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session,category_code_filled,brand_filled,hour,is_view,is_cart
0,2019-11-02 13:29:04+00:00,view,12300059,2053013556311359947,construction.tools.drill,bosch,69.17,513196170,00000510-834a-498a-9bed-561a90c5125e,construction.tools.drill,bosch,13,1,0
1,2019-11-01 19:06:53+00:00,view,1002544,2053013555631882655,electronics.smartphone,apple,458.25,514001239,000009c4-a1dd-4764-87d9-24f3d7e43c4f,electronics.smartphone,apple,19,1,0
2,2019-11-01 19:07:11+00:00,view,1002544,2053013555631882655,electronics.smartphone,apple,458.25,514001239,000009c4-a1dd-4764-87d9-24f3d7e43c4f,electronics.smartphone,apple,19,1,0
3,2019-11-01 19:08:13+00:00,view,1004659,2053013555631882655,electronics.smartphone,samsung,716.76,514001239,000009c4-a1dd-4764-87d9-24f3d7e43c4f,electronics.smartphone,samsung,19,1,0
4,2019-11-01 19:09:55+00:00,view,1004659,2053013555631882655,electronics.smartphone,samsung,716.76,514001239,000009c4-a1dd-4764-87d9-24f3d7e43c4f,electronics.smartphone,samsung,19,1,0

In [39]:
seq_df['time_gap_seconds'] = seq_df.groupby('user_session')['event_time'].diff().dt.total_seconds().fillna(0)
seq_df['log_time_gap'] = np.log1p(seq_df['time_gap_seconds'])

In [40]:
seq_df

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session,category_code_filled,brand_filled,hour,is_view,is_cart,time_gap_seconds,log_time_gap
0,2019-11-02 13:29:04+00:00,view,12300059,2053013556311359947,construction.tools.drill,bosch,69.17,513196170,00000510-834a-498a-9bed-561a90c5125e,construction.tools.drill,bosch,13,1,0,0.0,0.000000
1,2019-11-01 19:06:53+00:00,view,1002544,2053013555631882655,electronics.smartphone,apple,458.25,514001239,000009c4-a1dd-4764-87d9-24f3d7e43c4f,electronics.smartphone,apple,19,1,0,0.0,0.000000
2,2019-11-01 19:07:11+00:00,view,1002544,2053013555631882655,electronics.smartphone,apple,458.25,514001239,000009c4-a1dd-4764-87d9-24f3d7e43c4f,electronics.smartphone,apple,19,1,0,18.0,2.944439
3,2019-11-01 19:08:13+00:00,view,1004659,2053013555631882655,electronics.smartphone,samsung,716.76,514001239,000009c4-a1dd-4764-87d9-24f3d7e43c4f,electronics.smartphone,samsung,19,1,0,62.0,4.143135
4,2019-11-01 19:09:55+00:00,view,1004659,2053013555631882655,electronics.smartphone,samsung,716.76,514001239,000009c4-a1dd-4764-87d9-24f3d7e43c4f,electronics.smartphone,samsung,19,1,0,102.0,4.634729
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6727446,2019-11-16 19:06:10+00:00,view,6600378,2053013554189041997,computers.components.memory,geil,32.15,570721322,ffffb9ea-87d1-4f3d-b107-91b1bb087d36,computers.components.memory,geil,19,1,0,132.0,4.890349
6727447,2019-11-16 19:06:17+00:00,cart,6600378,2053013554189041997,computers.components.memory,geil,32.15,570721322,ffffb9ea-87d1-4f3d-b107-91b1bb087d36,computers.components.memory,geil,19,0,1,7.0,2.079442
6727448,2019-11-19 12:03:27+00:00,view,7203478,2053013553165631753,NaN,lego,244.54,573454547,ffffcdf8-f820-4b22-acee-d8c425b624fc,NaN,lego,12,1,0,0.0,0.000000
6727449,2019-11-26 06:11:34+00:00,view,28720653,2053013565782098913,apparel.shoes,respect,82.63,568409925,ffffecf5-59d6-42b2-ac84-143e24b06557,apparel.shoes,respect,6,1,0,0.0,0.000000
6727450,2019-11-11 08:33:43+00:00,view,13104503,2053013553526341921,NaN,powcan,398.98,558066678,fffffbbc-3c59-46fb-9165-fa46f027e332,NaN,powcan,8,1,0,0.0,0.000000

## Another part of Datetime

In [32]:
# 1. Dummy Data Create Karna
data = {
    'user_session': ['User_A', 'User_A', 'User_A', 'User_B', 'User_B'],
    'event_time': [
        '2026-03-12 10:00:00', # User A aaya
        '2026-03-12 10:00:15', # User A ne 15 second baad click kiya
        '2026-03-12 10:01:15', # User A ne 60 second baad click kiya
        '2026-03-12 11:00:00', # User B aaya (1 ghante baad)
        '2026-03-12 11:05:00'  # User B ne 5 minute (300 sec) baad click kiya
    ],
    'event_type': ['view', 'view', 'cart', 'view', 'purchase']
}

seq_df_2 = pd.DataFrame(data)
# Time ko proper Datetime format mein convert karna zaroori hai
seq_df_2['event_time'] = pd.to_datetime(seq_df_2['event_time'])

print(seq_df_2)

  user_session          event_time event_type
0       User_A 2026-03-12 10:00:00       view
1       User_A 2026-03-12 10:00:15       view
2       User_A 2026-03-12 10:01:15       cart
3       User_B 2026-03-12 11:00:00       view
4       User_B 2026-03-12 11:05:00   purchase

In [33]:
seq_df_2

  user_session          event_time event_type
0       User_A 2026-03-12 10:00:00       view
1       User_A 2026-03-12 10:00:15       view
2       User_A 2026-03-12 10:01:15       cart
3       User_B 2026-03-12 11:00:00       view
4       User_B 2026-03-12 11:05:00   purchase

In [34]:
seq_df_2.head()

  user_session          event_time event_type
0       User_A 2026-03-12 10:00:00       view
1       User_A 2026-03-12 10:00:15       view
2       User_A 2026-03-12 10:01:15       cart
3       User_B 2026-03-12 11:00:00       view
4       User_B 2026-03-12 11:05:00   purchase

In [35]:
seq_df_2['time_gap_seconds'] = seq_df_2.groupby('user_session')['event_time'].diff().dt.total_seconds().fillna(0)
seq_df_2['log_time_gap'] = np.log1p(seq_df_2['time_gap_seconds'])

In [43]:
seq_df.sample(4)

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session,category_code_filled,brand_filled,hour,is_view,is_cart,time_gap_seconds,log_time_gap
238724,2019-11-15 16:19:21+00:00,view,51600020,2134904980736311929,electronics.clocks,NaN,13.62,517207360,09127b68-ce87-4298-91f5-71316e49b2e5,electronics.clocks,NaN,16,1,0,0.0,0.000000
5997567,2019-11-07 04:38:54+00:00,view,1801766,2053013554415534427,electronics.video.tv,artel,146.88,513312212,e436f656-0a94-42d4-bc53-1873027c385a,electronics.video.tv,artel,4,1,0,0.0,0.000000
4982236,2019-11-04 16:25:51+00:00,view,1004833,2053013555631882655,electronics.smartphone,samsung,170.07,523181582,bd833755-7ba9-47ea-b5e1-1b54e70913e8,electronics.smartphone,samsung,16,1,0,35.0,3.583519
4014828,2019-11-12 22:29:36+00:00,view,16800247,2053013558316237377,furniture.kitchen.table,domini,347.50,528036434,98b14a5b-42d3-4d76-bdee-3f3c2093d0cb,furniture.kitchen.table,domini,22,1,0,24.0,3.218876

In [44]:
seq_df[seq_df['user_session']=='09127b68-ce87-4298-91f5-71316e49b2e5']

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session,category_code_filled,brand_filled,hour,is_view,is_cart,time_gap_seconds,log_time_gap
238724,2019-11-15 16:19:21+00:00,view,51600020,2134904980736311929,electronics.clocks,NaN,13.62,517207360,09127b68-ce87-4298-91f5-71316e49b2e5,electronics.clocks,NaN,16,1,0,0.0,0.000000
238725,2019-11-15 16:22:00+00:00,view,4200066,2053013552351936731,appliances.environment.air_conditioner,lg,1274.16,517207360,09127b68-ce87-4298-91f5-71316e49b2e5,appliances.environment.air_conditioner,lg,16,1,0,159.0,5.075174
238726,2019-11-15 16:23:51+00:00,view,4200066,2053013552351936731,appliances.environment.air_conditioner,lg,1274.16,517207360,09127b68-ce87-4298-91f5-71316e49b2e5,appliances.environment.air_conditioner,lg,16,1,0,111.0,4.718499
238727,2019-11-15 16:24:16+00:00,view,4200034,2053013552351936731,appliances.environment.air_conditioner,lg,1166.05,517207360,09127b68-ce87-4298-91f5-71316e49b2e5,appliances.environment.air_conditioner,lg,16,1,0,25.0,3.258097
238728,2019-11-15 16:25:19+00:00,view,4200034,2053013552351936731,appliances.environment.air_conditioner,lg,1166.05,517207360,09127b68-ce87-4298-91f5-71316e49b2e5,appliances.environment.air_conditioner,lg,16,1,0,63.0,4.158883
238729,2019-11-15 16:26:47+00:00,view,4200034,2053013552351936731,appliances.environment.air_conditioner,lg,1166.05,517207360,09127b68-ce87-4298-91f5-71316e49b2e5,appliances.environment.air_conditioner,lg,16,1,0,88.0,4.488636

In [46]:
seq_df['price'].describe()

count    6.616748e+06
mean     2.932733e+02
std      3.568747e+02
min      7.700000e-01
25%      6.945000e+01
50%      1.660100e+02
75%      3.607500e+02
max      2.574070e+03
Name: price, dtype: float64

### Price ke liye

In [48]:
# Sahi tarika:
from sklearn.preprocessing import MinMaxScaler
seq_df['log_price'] = np.log1p(seq_df['price'])
scaler = MinMaxScaler()
seq_df['scaled_price'] = scaler.fit_transform(seq_df[['log_price']])

In [50]:
seq_df['scaled_price'].describe()

count    6.616748e+06
mean     6.162788e-01
std      1.634895e-01
min      0.000000e+00
25%      5.058492e-01
50%      6.243706e-01
75%      7.304995e-01
max      1.000000e+00
Name: scaled_price, dtype: float64

In [51]:
seq_df.sample(6)

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session,category_code_filled,brand_filled,hour,is_view,is_cart,time_gap_seconds,log_time_gap,log_price,scaled_price
1673268,2019-11-09 18:56:11+00:00,view,1307310,2053013558920217191,computers.notebook,acer,257.15,515181427,3fb508e3-3bee-46fb-9468-7c1f49b53c38,computers.notebook,acer,18,1,0,28.0,3.367296,5.553541,0.684168
1260631,2019-11-04 05:29:27+00:00,view,28714397,2053013565069067197,apparel.shoes.keds,nike,94.98,550846295,301cfd5e-8c64-439d-958a-c37f1dd77640,apparel.shoes.keds,nike,5,1,0,0.0,0.000000,4.564140,0.548311
139723,2019-11-16 15:01:23+00:00,view,28715824,2053013565228450757,apparel.shoes,NaN,70.01,533859157,055beb77-c33e-44ff-b131-59bac760c13d,apparel.shoes,NaN,15,1,0,53.0,3.988984,4.262821,0.506936
376463,2019-11-20 14:40:22+00:00,view,7004027,2053013560346280633,kids.carriage,joie,230.38,516573585,0e57aaa5-3fdf-4030-a2a9-fdf5950ab7ad,kids.carriage,joie,14,1,0,9.0,2.302585,5.444061,0.669136
3553616,2019-11-04 04:50:45+00:00,view,4300291,2053013552385491165,NaN,polaris,25.23,553015579,871be878-7010-4545-890d-12214c6f00f3,NaN,polaris,4,1,0,12.0,2.564949,3.266904,0.370184
1283137,2019-11-06 11:28:15+00:00,view,26300078,2053013563584283495,NaN,lucente,316.10,567780959,30e59186-a7bb-4dd4-bf08-93e44f11974d,NaN,lucente,11,1,0,0.0,0.000000,5.759217,0.712410

In [60]:
seq_df['user_session'].nunique()

1376268

In [68]:
(seq_df['time_gap_seconds']==0).sum()

np.int64(1380608)

In [69]:
(seq_df['log_time_gap']==0).sum()

np.int64(1380608)

In [74]:
seq_df

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session,category_code_filled,brand_filled,hour,is_view,is_cart,time_gap_seconds,log_time_gap,log_price,scaled_price
0,2019-11-02 13:29:04+00:00,view,12300059,2053013556311359947,construction.tools.drill,bosch,69.17,513196170,00000510-834a-498a-9bed-561a90c5125e,construction.tools.drill,bosch,13,1,0,0.0,0.000000,4.250921,0.505302
1,2019-11-01 19:06:53+00:00,view,1002544,2053013555631882655,electronics.smartphone,apple,458.25,514001239,000009c4-a1dd-4764-87d9-24f3d7e43c4f,electronics.smartphone,apple,19,1,0,0.0,0.000000,6.129595,0.763268
2,2019-11-01 19:07:11+00:00,view,1002544,2053013555631882655,electronics.smartphone,apple,458.25,514001239,000009c4-a1dd-4764-87d9-24f3d7e43c4f,electronics.smartphone,apple,19,1,0,18.0,2.944439,6.129595,0.763268
3,2019-11-01 19:08:13+00:00,view,1004659,2053013555631882655,electronics.smartphone,samsung,716.76,514001239,000009c4-a1dd-4764-87d9-24f3d7e43c4f,electronics.smartphone,samsung,19,1,0,62.0,4.143135,6.576135,0.824584
4,2019-11-01 19:09:55+00:00,view,1004659,2053013555631882655,electronics.smartphone,samsung,716.76,514001239,000009c4-a1dd-4764-87d9-24f3d7e43c4f,electronics.smartphone,samsung,19,1,0,102.0,4.634729,6.576135,0.824584
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6727446,2019-11-16 19:06:10+00:00,view,6600378,2053013554189041997,computers.components.memory,geil,32.15,570721322,ffffb9ea-87d1-4f3d-b107-91b1bb087d36,computers.components.memory,geil,19,1,0,132.0,4.890349,3.501043,0.402335
6727447,2019-11-16 19:06:17+00:00,cart,6600378,2053013554189041997,computers.components.memory,geil,32.15,570721322,ffffb9ea-87d1-4f3d-b107-91b1bb087d36,computers.components.memory,geil,19,0,1,7.0,2.079442,3.501043,0.402335
6727448,2019-11-19 12:03:27+00:00,view,7203478,2053013553165631753,NaN,lego,244.54,573454547,ffffcdf8-f820-4b22-acee-d8c425b624fc,NaN,lego,12,1,0,0.0,0.000000,5.503460,0.677292
6727449,2019-11-26 06:11:34+00:00,view,28720653,2053013565782098913,apparel.shoes,respect,82.63,568409925,ffffecf5-59d6-42b2-ac84-143e24b06557,apparel.shoes,respect,6,1,0,0.0,0.000000,4.426402,0.529398
6727450,2019-11-11 08:33:43+00:00,view,13104503,2053013553526341921,NaN,powcan,398.98,558066678,fffffbbc-3c59-46fb-9165-fa46f027e332,NaN,powcan,8,1,0,0.0,0.000000,5.991415,0.744294

In [52]:
sequence_features = ['is_view', 'is_cart', 'scaled_price', 'log_time_gap']

print("Grouping events into sequential lists...")
# Har session ka data ab ek 2D list ban jayega
session_groups = seq_df.groupby('user_session')[sequence_features].apply(lambda x: x.values.tolist())

Grouping events into sequential lists...

In [55]:
session_groups

user_session
00000510-834a-498a-9bed-561a90c5125e                [[1.0, 0.0, 0.5053023397225167, 0.0]]
000009c4-a1dd-4764-87d9-24f3d7e43c4f    [[1.0, 0.0, 0.7632679460139488, 0.0], [1.0, 0....
0000189b-6d2d-45bc-a65c-3a9d94e330a4                [[1.0, 0.0, 0.2530873103778527, 0.0]]
000029a6-1986-4a71-8139-53669c1adaba    [[1.0, 0.0, 0.7042206281404793, 0.0], [1.0, 0....
00003dca-5a5a-4af2-86ef-9851ceb02a2b    [[1.0, 0.0, 0.5880030573018032, 0.0], [1.0, 0....
                                                              ...
ffffb94a-cea4-429d-ba4a-7e47a6f28171    [[1.0, 0.0, 0.6275241828533435, 0.0], [1.0, 0....
ffffb9ea-87d1-4f3d-b107-91b1bb087d36    [[1.0, 0.0, 0.44746721585529425, 0.0], [1.0, 0...
ffffcdf8-f820-4b22-acee-d8c425b624fc                 [[1.0, 0.0, 0.677291735891466, 0.0]]
ffffecf5-59d6-42b2-ac84-143e24b06557                [[1.0, 0.0, 0.5293981536199067, 0.0]]
fffffbbc-3c59-46fb-9165-fa46f027e332                [[1.0, 0.0, 0.7442940653881134, 0.0]]
Length: 1376268, dtype: object

In [57]:
# Aligning Targets (y) with the sequences
y = np.array([session_targets[session_id] for session_id in session_groups.index])

In [56]:
session_targets

{'00000510-834a-498a-9bed-561a90c5125e': 0,
 '000009c4-a1dd-4764-87d9-24f3d7e43c4f': 0,
 '0000189b-6d2d-45bc-a65c-3a9d94e330a4': 0,
 '000029a6-1986-4a71-8139-53669c1adaba': 0,
 '00003dca-5a5a-4af2-86ef-9851ceb02a2b': 0,
 '00004022-c43d-4223-b5ad-da2b0e59b84f': 0,
 '000077fb-5f32-4a86-a179-2bbf8c34e9d8': 0,
 '00007d1a-aa00-4a01-b03c-879973251c53': 0,
 '0000a101-4e26-488a-85e9-f666baec0fc5': 0,
 '0000ae8f-570d-4a89-9690-6f22050b8175': 0,
 '0000be71-fe05-4b44-af8e-e8de041095d2': 0,
 '0000d24a-8726-4415-b256-4bc0e7b8c14f': 0,
 '0000d442-3df2-4942-81e3-3ff3d5385701': 0,
 '0000d540-b6d7-4ad0-845a-2055cb5c6bd8': 0,
 '0000e7f9-2292-4e7b-8844-0faa14df9a02': 0,
 '0001170e-5cd1-49be-a351-a4ab375b8a9a': 0,
 '00011aca-0f0b-484c-b944-b36edb777492': 0,
 '00013570-3379-43cf-94f0-454a55834f55': 0,
 '0001367d-b671-412b-af55-b831628a6f54': 0,
 '00017baf-3bda-4bc5-945c-63c08676f288': 0,
 '00017f39-e983-4655-9db2-ae3bea7f0071': 0,
 '000199a3-437c-4ae8-b26b-01e0f34c1418': 1,
 '00019c1f-02da-48ea-85f9-a8b769cd110b': 0,
 '0001a1b4-7adf-4c7a-9230-fdc1f1ae4e7c': 1,
 '0001b18c-ed04-46b4-8d51-e567aac896c5': 0,
 '0001b609-dbb0-4c1e-a036-2da4048f5760': 0,
 '0001c990-bf26-46ba-9723-276014ad799d': 0,
 '0001ca7b-f310-4547-9c1c-25ae985d67ab': 0,
 '0001d184-5468-48ed-9921-558cb1d704b8': 0,
 '0001d965-19b9-4ffc-a211-b71a73322926': 0,
 '0001dfeb-436c-4f43-b7bd-0575fee6061f': 0,
 '0001e60a-af51-40fb-a0d6-27e84223b0ad': 0,
 '0001ef1e-22bc-47d1-b429-4479b29adfd2': 0,
 '0001efdd-9649-44cc-9911-ca001c9844d5': 0,
 '0001ff3c-df26-4a66-a3d9-b9955a780003': 0,
 '000204ef-9c82-421b-a5b1-b982c31b2299': 0,
 '00020ffd-a607-4570-9da2-65ee82680a54': 0,
 '000210bc-245f-47f6-a58f-e0a6586496d5': 0,
 '000211a5-3f6b-4563-ac7e-da49604ca683': 0,
 '00021c98-687c-4fbe-b432-92929ab48eb1': 0,
 '00022399-61de-424a-8911-9b6b049a4a32': 0,
 '00022d99-0df7-426c-a93e-71a62734677f': 0,
 '00025740-6e46-4e58-a51a-3d0093141d88': 0,
 '000259d7-f50b-440f-8605-78e660096afc': 0,
 '00025fc8-8ecd-4c34-a880-f3d7f73d553f': 0,
 '00026a83-dea6-4efd-93e8-ab3e52e7673a': 0,
 '00026fdb-9b76-4871-b565-898ef9d30520': 0,
 '00028c1f-f789-44be-a509-154d0f93ad74': 0,
 '0002a8a3-21eb-41af-9d6e-6de129706c8f': 0,
 '0002c06f-a314-4969-bf5d-d3094539288a': 0,
 '0002c67e-91c9-44d4-8fed-ee8298231db0': 0,
 '0002c976-7202-4b13-b335-0fe3af358c55': 0,
 '0002d13f-d666-45f1-92c2-a44581e33525': 0,
 '0002d70e-7a99-4601-a9ea-61539fb4c883': 0,
 '0002e288-569b-4642-8a82-b183ee537259': 1,
 '00030ff3-dc6b-48b9-be20-025715e70d67': 0,
 '0003277d-571a-4ad6-85b3-9d92d7e46ae0': 0,
 '00033d58-4d4e-424d-8723-24700639b0f7': 0,
 '00034bfd-f981-4997-b61a-4f69803259b7': 0,
 '00034df0-0894-4f9a-85ec-731dbc7d620d': 0,
 '00035bd6-5e36-4dec-9f68-6161eb4e7917': 0,
 '00035f1a-f4f4-4170-8207-6406ec0259d7': 1,
 '00035feb-7620-410c-984b-b7d5a5b4fc93': 0,
 '0003799e-9f33-462c-a46e-b23643fb3741': 0,
 '000390da-1133-4577-9060-1e671acc1f8c': 0,
 '000396ce-ac40-49b2-bce6-be288d13d251': 0,
 '0003bb64-7420-4874-8ebc-d0a5e10eb67a': 0,
 '0003bf61-bada-458a-98a0-40f185b00322': 0,
 '0003c40f-13f7-411e-82cf-8633f7c0c127': 0,
 '0003cd86-09b2-4b93-8910-8509023bfbac': 0,
 '0003d2b1-c6c5-4963-a943-2b1d378c2b75': 0,
 '0003d309-361e-4962-bd6f-6528bdde9171': 0,
 '0003dbac-f398-420d-bba9-71450a108f50': 0,
 '0003de99-f459-415c-ab06-6ca8ce44c58d': 0,
 '0003e038-48fe-46f0-8343-fc4d721b109b': 0,
 '0003ea35-72ae-4c29-99b9-d85b85868b52': 0,
 '0003ef27-6d3b-4a6b-a8f8-d75285305ff4': 0,
 '0003fbe5-8a6a-4a56-b925-eaa48a7c7bc4': 0,
 '000441b1-66c6-49f7-9c4d-2f236a4c02c1': 0,
 '00046b13-1825-44c8-b136-9831626905c7': 0,
 '00046db5-9cac-4f48-85f7-cf0f26b538e0': 0,
 '00048083-ce0e-4462-b6c5-1b61dcbe43a1': 1,
 '00048a82-fc4c-4f99-b927-53d495b32eb8': 0,
 '000490bb-9d08-43ff-8ff3-9332ed4fa00f': 0,
 '0004947d-f145-468c-8f8d-84a5f1d76187': 0,
 '0004a485-933c-43fa-8c24-708204724d4f': 0,
 '0004a582-9137-4a9b-9695-b743eaea850f': 1,
 '0004a69b-0736-4717-94ab-61540df5f26b': 0,
 '0004b2ca-e866-460c-8248-02b1602da1c4': 0,
 '0004b526-db41-4c5c-8464-b06b602bc9cf': 0,
 '0004b77e-8f3a-45a5-b69c-80983d176d6c': 0,
 '0004bf4c-8fd4-4309-b5c4-b3f2ec348e11': 0,
 '0004df88-ee8b-4ab9-9804-45f05add05f8': 0,
 '00051140-2252-48ce-8589-b5f019a8015a': 0,
 '000521d9-15fb-4166-825d-89fcaa887452': 0,
 '000530fa-854b-4343-920a-07e7c2f57f4f': 0,
 '00053573-4a16-45fe-8353-916a6beb9f68': 0,
 '00053694-56b1-4ca4-b682-0b52e03bfec4': 0,
 '00053722-9cf0-4053-b91b-c1c699bc5689': 0,
 '00053c28-d182-42f2-b1b5-f525a622d96e': 0,
 '000559c0-fec5-42f7-b1e3-9f5a4d04e460': 1,
 '00057cf3-246f-4843-bae1-d16a1ea32183': 0,
 '000581af-da49-44a0-b2a4-a0e84382951f': 0,
 '000583d9-a9c5-40eb-9b3e-2e6d95515042': 0,
 '00058e0a-2d65-1283-f1a3-d9aefa6fcada': 0,
 '00058f8b-30e4-401c-ae00-eec9ceddfe40': 0,
 '0005a7d1-7eac-4226-9535-189eb3a7de56': 0,
 '0005cbef-7043-4832-a483-7d109008ef1a': 0,
 '0005d58b-ef5c-48d5-a9e1-822280826293': 0,
 '0005e9c7-aa37-476c-8f3c-69e45c714abb': 0,
 '0005ebb0-ed47-4eae-a46c-4d429dfd276c': 0,
 '0005ee26-e436-dace-11be-3b8fe6f786f2': 0,
 '0005f025-d675-4344-897c-68897a6ea601': 1,
 '0005f2a3-c212-46b0-9713-0afe85628f2a': 0,
 '0005f371-924a-4a53-b0f7-2775ad0e6bf7': 0,
 '0005f3e5-ef5c-4d84-b201-a1ce2a813b45': 0,
 '0005f6d4-7f9e-434a-8edf-a715009b2a7f': 0,
 '000607ca-4dd7-4c0c-ab22-2c099a6a027d': 0,
 '0006134d-cac6-4a9e-a982-e8d3c1ba22cf': 0,
 '000614f6-9f94-b420-e159-40780d323fc7': 0,
 '00061e84-3908-430b-9453-b185aab2d3b5': 0,
 '00064be1-294e-4454-9c31-642fd5b6ce89': 0,
 '00065068-67d1-4883-8c5c-017c496c597c': 0,
 '000665d4-4472-4e19-9517-a45feae32f5b': 1,
 '000667c6-b580-48c6-b650-a07969b4e15f': 0,
 '00067110-7e9a-4506-aa88-aaa933dc880b': 0,
 '00067f60-9efc-4985-ae73-04397d2316d2': 0,
 '00068bad-fc40-448f-9282-8c56e1921856': 0,
 '0006aafb-1b95-4383-8e7a-6c99bb757e97': 0,
 '0006afcd-fa4c-4d1d-a9ab-571cfdcfb79f': 0,
 '0006b22b-efa7-40a2-867f-7818e6eca5af': 0,
 '0006bf4b-51c6-4649-a325-84482543fec1': 0,
 '0006d193-da98-4e6f-869a-b6060ae10339': 0,
 '0006d3d1-6e80-4876-ae65-d073551701c1': 0,
 '0006dbff-4c32-413a-a52d-f4c8269b1d79': 1,
 '0006f116-ba9a-4e9a-a92f-f71f64feed44': 0,
 '0006f937-0ed8-4c37-a160-e66162fe19f4': 0,
 '00070beb-de17-4f65-866a-69eb1a455166': 0,
 '0007111d-0526-4561-b47b-fc5e16961e79': 0,
 '000712b3-ca94-421f-b126-fbff68dc4776': 1,
 '000712c0-4d7e-4dc5-9932-2fa469f5fc60': 0,
 '00071aac-4f57-442b-a52b-f8f7cedf2421': 0,
 '00071b49-7f92-4e47-8384-095e64d78c10': 0,
 '00072231-a36d-440d-bc81-47329c6b047c': 0,
 '000723ea-3fe8-4b89-bb0f-5c4cc1d43060': 0,
 '00072b2c-cf71-4f98-8160-416234a749ed': 0,
 '00073120-f5b4-479d-b583-f72ec32c81a6': 0,
 '00074e23-b9c1-483b-8ffd-6c0914a10973': 0,
 '00075c4c-e380-44e5-a093-bb7166d99c84': 0,
 '00077187-2140-4a0e-a806-3d20b8d533dc': 1,
 '0007758a-ce73-47f9-a61c-f9f44f40d252': 0,
 '00077cc5-e1f2-4cdf-b596-e163b59a06bc': 0,
 '000783b7-d621-48c3-8e4f-96baf0b312bc': 0,
 '000789af-458b-47b9-9df9-c0f1ab442681': 0,
 '00078b77-972a-4afa-abca-5bd6563e60c8': 0,
 '00078c86-e30d-4b07-b53c-becc305e0862': 0,
 '0007a10a-31e7-4bd1-b5ff-f06fe5dc9029': 0,
 '0007b5b3-0bcb-4df0-993b-39d12a0e58dd': 0,
 '0007c63b-16f1-404c-b6bc-f123804485d4': 0,
 '0007cc05-825d-4137-85b2-c8de23bd98f2': 0,
 '0007d9fb-853c-4b52-bae0-1461ded022e2': 0,
 '0007e937-551d-42df-a4e6-f792c2b6a1de': 0,
 '0007f238-2612-dfbb-08b7-53974443de63': 0,
 '0007f945-0838-4288-a819-56bc96ac09a4': 0,
 '00080171-595d-469b-8573-d064ad27cd12': 0,
 '000810bd-f0e9-4b78-90cd-b02c7463d000': 0,
 '00081da4-ef57-480a-a083-914f0d8020a5': 0,
 '00082674-12de-47d0-8fe3-efd70ddde8c2': 0,
 '00082ce7-f968-402d-b899-90bd0b125fd2': 0,
 '00082eb0-5896-4ad3-b418-c9606deeebf6': 0,
 '00083dbb-2064-4d96-aa1f-140026e2d67b': 0,
 '00087a56-7c2f-4268-9e7a-3d1dbc3b7bb2': 0,
 '00089730-9dd0-4768-8910-efc2abb87d90': 0,
 '00089e52-feab-4211-b269-c5a3eb27c11f': 0,
 '0008b535-1132-40c0-843e-a0d78a659c4e': 0,
 '0008fa53-31d6-4749-b943-468be501b8e2': 0,
 '00090eab-c1f8-4741-96c4-828efff24e96': 0,
 '00091202-8abc-440c-905f-bd75fec7b840': 0,
 '000917c6-5f55-41ce-a56f-d98750e4c484': 0,
 '0009189f-8895-42fa-ad59-a483a52555c2': 0,
 '000920d3-efa9-4a05-9f16-435ec9799bd7': 0,
 '00092365-8f79-48de-8a0d-81620eb604ca': 0,
 '0009263c-3964-474e-8aa5-8af1e6eab791': 0,
 '00093a31-ac7c-4449-9dfc-5d67f7157ce6': 0,
 '0009478b-10cb-4abf-b36f-cf568c11303b': 0,
 '000954b4-c838-47cb-adc7-d049ec17e524': 0,
 '000959d9-0696-46a3-b968-c2d5d46107e1': 0,
 '0009601b-285e-4620-9bc8-6c0bc66e63fc': 0,
 '0009637a-5d57-489d-b88a-227bb4944193': 0,
 '000966a4-4fd4-4013-b094-d13d1d70f39a': 0,
 '00096a4c-18ae-4b9d-9b06-85e3e166addd': 0,
 '00097ba8-be90-47f9-998f-33d744dd5b22': 0,
 '00098838-00ec-48f6-b260-87b26aa0bc8f': 0,
 '000990d8-3962-4e52-9c88-8c011e888126': 1,
 '000991c4-6bb2-49f4-bb92-3057a9c247d5': 0,
 '0009a4b1-b7f6-47ec-9189-9040c7c567e7': 0,
 '0009b163-bc93-45d8-9fb9-49ae3a4ad9c0': 0,
 '0009b704-1186-4217-b7a8-08608fb11141': 0,
 '0009b84e-a910-4717-a0bd-44a72c5f5bf4': 0,
 '0009c064-4cbb-40d7-9b68-9a82c479e666': 0,
 '0009c4df-7e73-4c9b-a00d-5dcb2c5cf055': 0,
 '0009c74a-de57-4fb5-ba2d-fdda6d785d48': 0,
 '0009d81f-14fb-4be0-b569-f7b50d75a458': 0,
 '0009d83a-4fd6-4ddf-8479-482e1b3dcd51': 0,
 '0009fdb1-33ae-4740-b88b-27cfac163f44': 0,
 '000a1d10-f23a-456b-98c5-e33b3cfd6ce1': 0,
 '000a2c7e-5c12-4ed8-9077-0708070cd341': 0,
 '000a3a08-2ab9-4d6f-a04b-ec9f27540937': 0,
 '000a41ec-4af1-4ddf-9efd-342219ee3fb2': 0,
 '000a4333-d44a-45ac-9658-31cad0fb651d': 0,
 '000a4e00-153d-4742-9158-dfb545dd7bf8': 0,
 '000a58f1-b0e9-47d9-9921-a8f51ddf7e49': 0,
 '000a64df-8c7d-4d39-8fd5-ebc0176f207d': 0,
 '000a6604-997b-4ff6-b9ab-9ad422fa65fa': 0,
 '000a78b2-b9be-471d-a7d5-ee4a409cb907': 0,
 '000a858d-aeaa-4745-812d-79d7f6936cd7': 0,
 '000a8afd-7e76-471c-b651-95652e296eb4': 0,
 '000a8f80-361d-4b35-86fd-74add8575fcf': 0,
 '000a8ff9-c7cd-4ab9-8ac0-117ae80ec2fb': 0,
 '000a9e2f-894f-4b20-83a5-8c5b5ce480d6': 0,
 '000aaf10-e279-4167-b44e-dac27821fbe6': 0,
 '000ab2f7-60c1-4235-b810-1e31c7a1a136': 0,
 '000ab6b7-cad7-4dac-b2cf-0a449bb2178f': 0,
 '000abf18-6705-4664-a0c8-1514b04d8651': 0,
 '000acc60-778c-4363-a4af-9ea5a1abe5e2': 0,
 '000aea45-ab51-4fd4-a0be-566577ea85af': 0,
 '000af92a-8985-45a8-9c9a-73b0e8a687e9': 0,
 '000afa4f-9bc3-4fd0-a054-79055bd53758': 0,
 '000b0306-ddaa-468c-b84b-e887b2d07d7c': 0,
 '000b0618-3d19-4872-b6c1-5a327b7814a8': 0,
 '000b36dd-0c43-4d28-90e0-9c277296462b': 0,
 '000b4294-fd83-44a4-b446-9c3d785c348d': 0,
 '000b4ce9-4d92-46ec-85c2-2ed9b266e5ce': 0,
 '000b52ba-d4d9-4d34-809d-95ba1a10e713': 0,
 '000b5414-4296-423e-ae47-2f4283cbe386': 0,
 '000b7623-c834-428b-b547-e00eec9ad766': 0,
 '000b795f-e184-46be-bf12-c07cd575a46b': 0,
 '000b8010-49cf-479b-a25d-2ac4fe66f3b4': 0,
 '000b89d9-5ca8-4144-a1c2-0cff38915a28': 1,
 '000b9fe3-20b6-4483-a75a-9675d215654b': 0,
 '000bb1fd-8515-4a7c-b987-4e318c48f260': 0,
 '000bbb2f-1dbd-4197-ba26-07a1c8fc9299': 0,
 '000bbca3-45c9-419d-aae1-f189614385c2': 1,
 '000bc879-ab51-4c2e-935a-5780bbd84417': 0,
 '000bcd70-7620-4274-8d34-a9997e0da501': 0,
 '000bddd2-c3e2-4fab-898e-24c48dd323c6': 0,
 '000be7d0-fa14-4dab-9526-cb99dbd8a705': 0,
 '000beb0b-443c-4e0c-8478-063698783272': 0,
 '000c0b7d-8b1e-4962-a732-1e7476a69c67': 0,
 '000c117e-6e5b-4159-abae-a259fedbba28': 1,
 '000c1ad5-c46f-4293-b979-23429bdbfec1': 0,
 '000c2d87-e5bd-4b07-8037-00106c3a0a06': 0,
 '000c6751-9464-4462-9d16-adec3c499ad9': 0,
 '000c6a37-e8f2-4710-bfd3-afcbd8ce4372': 0,
 '000cb116-2aec-4238-a38b-3caa157d7ff1': 0,
 '000cb669-b158-4fee-b062-a6f5d9c5680f': 0,
 '000cc516-6038-4b9d-aaf7-2cb5eff83ae7': 0,
 '000cc850-9d2b-4bfd-9dfb-68e61e396a72': 0,
 '000cd375-7d7c-4062-8ce4-e1f60c557caa': 0,
 '000cdb9d-5f9b-48df-b638-37be2a3e7434': 0,
 '000ce03f-756e-413d-9033-39b69937fdb4': 0,
 '000ce7de-1db2-4d63-8308-854c4e34d05b': 0,
 '000ceef5-afad-4a45-94fc-3d861eaae590': 0,
 '000cf5a8-b570-4287-bb77-8481894cc587': 0,
 '000d10e9-9de7-4f44-b863-6dc7eb0d4368': 1,
 '000d14c9-f88f-4f80-bc78-8646692936bc': 0,
 '000d33a0-a3ad-467e-b6c4-239e8576f814': 0,
 '000d3e53-b113-440d-b359-92aa745bc8c4': 0,
 '000d4944-e9f6-430f-ae5b-86e1649f8572': 1,
 '000d4caf-91b7-4a1f-b243-1e4c7665c276': 0,
 '000d642e-2438-4b12-8076-3b52a93fbf5b': 0,
 '000d6780-3f8a-44e7-8089-1d29fa52b1f3': 0,
 '000d6c47-60f0-4ca8-99dd-596b626b7fbc': 0,
 '000d8eed-8f45-48b8-8008-1bcdeda431f9': 0,
 '000da114-141d-4d90-a99b-de93b6d55295': 0,
 '000daa37-4221-46cd-8bb3-74446dd34780': 0,
 '000dcb84-409f-4d1e-a802-080492795062': 0,
 '000dcdff-fe37-4a46-ab68-795bee167891': 0,
 '000deada-c6aa-4346-a22a-247f97c806e3': 0,
 '000dec01-108f-4555-a7cf-dc32648794cf': 0,
 '000dfe11-8231-4446-b78e-db4efbf73a2c': 0,
 '000e1443-e950-4012-ad21-fecbe39d8085': 0,
 '000e1da4-b752-4b1e-ab02-ee160d0525e1': 0,
 '000e319d-012d-4e3e-91de-91cfa8fa767f': 0,
 '000e3585-63d6-40a7-92a0-6e929579b961': 0,
 '000e4909-f91d-4c6c-9435-db0782199be9': 0,
 '000e583a-1095-42bd-9637-822bc6247902': 0,
 '000e6343-3d07-4655-8f4b-939b5908f3d2': 0,
 '000e64f9-66b4-41f1-9382-6a88b456b644': 0,
 '000e72b8-e1be-42d2-858f-93fd657aa591': 0,
 '000e74b7-0b08-4ad0-b2e9-92ab4ff85f44': 0,
 '000e84f5-0903-47ff-b1a5-f0b2a472e0b5': 0,
 '000e876e-f9ee-4b18-beb2-835a1297953b': 0,
 '000e8d03-7458-4eda-bb7a-a0a5fce56e34': 0,
 '000e9511-2500-4945-8dba-9001aa397a73': 0,
 '000e9ece-4c73-4b90-810b-cb9b89e9417d': 0,
 '000edd92-9e9f-4a6d-9104-64b0f69765be': 0,
 '000ef36e-2cb3-4535-9dda-1d88713f74d4': 0,
 '000ef9db-60c6-47b2-9c9f-c2e008f9fded': 0,
 '000efc72-7b3d-43a8-bdf6-3d012316ab64': 0,
 '000f0ea6-eba5-4357-9907-177652430c78': 0,
 '000f1907-6d0d-4768-b319-e73b493438f1': 0,
 '000f27d2-fda1-4928-82b1-453d4621d710': 0,
 '000f3188-33bc-4a17-933b-c968a951f0cc': 0,
 '000f416b-461b-476a-ac1f-c72356651171': 0,
 '000f4ada-31df-4996-800b-cb1a1ca88fc5': 0,
 '000f4c3b-20c1-44e4-a9f3-8bc9169e6830': 0,
 '000f604c-3afa-4c97-8a69-b01503269392': 0,
 '000f6d9f-4dba-4dcf-87fe-14d996482dae': 0,
 '000f7609-d3d2-47be-9d61-c2e061999477': 0,
 '000f787c-130d-47e3-a0d5-b49a85c01902': 1,
 '000f8ead-7756-4dc5-8755-6ace25296fcd': 0,
 '000f8ec2-272b-4f51-a7a8-c8f9f708ab51': 0,
 '000f9286-0882-4239-a9ac-72e4b0041070': 0,
 '000fbc1d-3b97-40ac-b490-fb7325f875ba': 0,
 '000fbecd-b06a-46a3-9418-06e07b82f40b': 0,
 '000fc8c8-9172-4dbb-8f36-8d82a3879d30': 0,
 '000fcb7d-56d9-437f-b719-f422955289d7': 0,
 '000fcbec-75cb-4ff2-b21a-73ba7fab85c8': 0,
 '000fe0d0-741d-4567-8217-86a6ca8414c4': 0,
 '000fe244-ae47-4049-9537-a17723295bf7': 0,
 '000fe5b9-08fd-45a4-bc51-04ea468ad2b8': 0,
 '000ffb9e-317e-4c65-babf-5a5b9697016a': 0,
 '00101078-4e0f-4948-811b-b96fd234beb3': 0,
 '00101df0-40fd-4a3d-9ceb-d87ed410e805': 0,
 '00102213-7a74-4c70-be00-507c72a22ce8': 0,
 '0010288c-88aa-4df3-9c68-8e3576d68106': 0,
 '00102c62-2a53-481a-86fe-60e4a1e1dd39': 0,
 '001033d4-84f4-416e-b12b-8aafaffde45e': 0,
 '0010377f-71e2-9821-6cbd-3a7901e94c2e': 0,
 '00104447-c015-44bc-907b-87e46b7a7147': 0,
 '00104b8c-d7cb-4e46-9b3d-c7c03a181015': 0,
 '00104cf6-289e-4ee4-a60f-900601d6de2f': 0,
 '001054cc-ba25-46a3-b4b3-808b9e5960a0': 0,
 '001054db-8a3c-43c6-bc20-56740df69577': 0,
 '001060e5-1a05-42fe-ac6c-97fad8316e1e': 0,
 '00106b8c-068a-429b-b1eb-aa2339405783': 0,
 '00106d3b-5bf0-4fb5-947e-d8bc92358bd5': 0,
 '00108e98-51af-40b4-8045-dfd6515c86bd': 0,
 '0010947c-ad7c-477c-b11b-b2c6fc5a20d1': 0,
 '00109dd7-113b-4f84-99f7-25022b0105c7': 0,
 '0010a6ac-aa81-457e-bd60-5fb62a17c3de': 0,
 '0010af2b-787b-45e2-ae88-a633eb5b5f8a': 0,
 '0010bee4-8b8e-4a09-b7d5-0ba23c897c4a': 0,
 '0010c000-11be-414e-b2a0-6b813d95c23f': 0,
 '0010e495-4daf-42fc-9627-af46e3ce09a9': 0,
 '0010efff-703a-e132-d52f-60b96db41362': 0,
 '0010f121-03fc-4c16-bca2-7c3242b2e290': 0,
 '0010f3ab-7876-4469-9f0f-3b1253dcc3b9': 0,
 '00111315-fbd9-424f-bc2e-be416773b10d': 0,
 '0011202d-dfad-40a6-9c4c-0fc42558789f': 0,
 '00113283-9564-42f2-9327-77cf8bc30c9f': 0,
 '00113428-4cc1-4df4-99bd-d697f22e3abf': 0,
 '00113b0e-dd44-4dc5-b874-151f903dbfe4': 0,
 '00115427-5c9d-4d99-aa0c-702b95531022': 1,
 '00115aba-cd4f-4ebb-99d1-ef24c87fcb0f': 0,
 '00117281-88b3-416c-b5e3-c0fae1bf6f23': 0,
 '0011734b-a1ad-4057-a358-9e715ff96fd7': 0,
 '0011a36f-d950-4bd7-ae75-35143a7d5152': 0,
 '0011b271-24dd-4057-b138-24585c2e2006': 0,
 '0011b5d6-82ba-491b-a021-fa197733686d': 0,
 '0011b96f-99b2-4d10-bfe6-4e05b06111dc': 1,
 '0011c2b2-158b-4325-83a6-6c59a35d349e': 0,
 '0011c334-2aa8-4c32-ae20-cb5e77237b49': 0,
 '0011cf6b-c1c8-437f-8dc7-ed420bab469a': 1,
 '0011d5b0-2ffd-4fe7-8fcd-35eeed4db732': 0,
 '0011dbc5-2892-4d9f-a52a-a09f016699c1': 0,
 '0011dc04-61a5-4a57-8d4f-2687cfa7764e': 0,
 '0011f465-160f-429c-8f66-3639a37c49ba': 0,
 '0012000f-5802-461c-a7ef-a91329d05965': 1,
 '001202f6-51f5-4441-842a-c0c898ba8480': 0,
 '001207fa-c78d-4b50-9649-1c1f324a65d6': 0,
 '00120d1f-cc91-453f-b6b7-4ca36565d2a9': 0,
 '0012105a-8615-4a8b-915d-ea853f85f997': 0,
 '0012124d-788e-4e6a-9c1b-56e540001508': 1,
 '00124240-d762-4048-9ea0-cdf8764f6755': 0,
 '001246e5-efee-42ad-8745-5cb5775d7435': 0,
 '001248af-2899-41dc-ba39-b02d227f9473': 0,
 '00125f7c-70ff-42e3-a30e-2d12fabebe10': 0,
 '00127e4b-be69-4bc1-b1a2-4aa1d7ce841e': 0,
 '00128661-9009-451b-8bef-f8ecbf7b35b4': 0,
 '00128e51-ab0e-4dfa-9de4-686317b656f7': 0,
 '00128f3a-1af2-454a-8130-7768daf1b711': 0,
 '0012a7a7-8670-4474-8032-21e943f47090': 0,
 '0012af45-a61a-499b-bf48-06330c3ca417': 1,
 '0012b1ea-8a46-49b7-8bdf-f36e3d1cd050': 0,
 '0012b499-2ea9-4689-ac28-7783c8ccf3fa': 0,
 '0012c610-356d-41e9-8124-b24d630d9008': 0,
 '0012f931-ca45-441c-a632-9231aaed27e9': 0,
 '0012fe9d-9a6c-4a41-9e77-8b8dad44746b': 0,
 '00130207-0622-4a65-8e7c-ec8dff9df4f3': 0,
 '00132187-a431-4266-8eef-9590e748ff87': 0,
 '001349aa-03d7-c47d-9acc-15fad08112af': 0,
 '001355fc-a028-4e7d-a6e4-877951e004d4': 0,
 '00135ce5-2bde-448c-8018-b7571d0d73a2': 0,
 '001362f7-576b-446d-bafb-508fa395ecec': 0,
 '0013650a-05ff-4f25-a9ea-1fc915269b0a': 0,
 '00136b98-fea6-4429-b86a-01e034e03d26': 0,
 '0013865c-8fcf-423f-96c8-33afd0d97d9f': 0,
 '0013a0a0-0b4b-475c-a971-2a70827c0d09': 0,
 '0013a24a-8f60-419f-8771-62c50c45e95d': 0,
 '0013ad0d-eab7-4984-a0a5-95ee1742fd76': 0,
 '0013af22-dd96-41d6-8cc7-3d85c59f0f12': 0,
 '0013b329-91b1-47a1-988e-e056fc011379': 0,
 '0013b609-7f05-4dca-8c75-b04b57aa36ef': 0,
 '0013b927-130c-44c0-9cd3-cead6cb51889': 1,
 '0013bacb-dea6-445c-ba47-58148fcf66eb': 0,
 '0013bb9a-e46d-46cf-a627-1c44e2651a19': 0,
 '0013c23e-cc64-4d71-860c-ef772c1737af': 0,
 '0013c24f-99c4-416b-8dd5-77661dde0fb6': 0,
 '0013e26d-0f20-4022-9ce0-101615f89eee': 0,
 '0013e753-6100-4d08-a17c-56580d5d5d9b': 0,
 '0013ec54-1e0e-4122-84b0-4afc90827907': 0,
 '0013f3ae-efe9-40ae-8cf4-c13ea38cbd55': 0,
 '00140eb9-03f2-4fc7-9200-de6204a26b61': 0,
 '00141245-e17f-40f4-86cd-0e378ed73e23': 0,
 '001413e0-268b-41e8-a2f7-d71c73f446f0': 0,
 '00142a8a-af6d-46d0-bba9-19fb6a1f0a29': 0,
 '00142e76-51ff-4f21-8433-098396b99633': 0,
 '0014387b-1248-433e-af79-3818378816c9': 0,
 '00144273-40e3-4ddc-9798-0863f440dfc7': 0,
 '00144ba0-e8de-4c82-a86c-dbb6e5dd3656': 0,
 '001454a6-6e9e-4ba8-bfd0-16a605532b1d': 0,
 '001458a5-1587-4cc3-8df8-1f7ce70e410f': 0,
 '00145f87-37ff-4e80-929e-eceae85082e7': 0,
 '00147187-c26e-44a6-b679-65ae708ad814': 0,
 '001475f9-98b1-447b-a914-6aefab0fb39d': 0,
 '00147cc2-67c1-40b0-a9ff-5f7d99cf31a8': 0,
 '0014845b-7c65-4a22-b618-53778ac7ce7c': 0,
 '00149660-4d60-4d11-b8bc-3a06e5fed4c3': 0,
 '001498cc-c671-4692-9dc7-06d045d7c756': 1,
 '00149d64-b56b-409d-bb7f-ecaa7508ca1b': 0,
 '0014a687-8480-40e5-9542-5447c20edaf7': 0,
 '0014a74f-ee14-4e2a-89ca-71dbaeca32e6': 0,
 '0014b965-1914-41a9-854b-ac50b14fff22': 0,
 '0014d4ad-6c44-435a-804c-800f9e70d342': 0,
 '0014e5e3-16f0-49b3-8fbe-4b069ebd400f': 0,
 '0014f313-e572-404d-a4d1-de9f868c7e0c': 0,
 '0014f62b-d1f8-42b6-a726-c5f2137d736f': 0,
 '0014f698-6529-4c01-b833-37be04598d83': 0,
 '0014fbef-874e-44eb-bcde-fb13dad18e6f': 0,
 '00150d63-901b-4ba0-811e-40ab93046eac': 0,
 '00153170-c09f-4434-a1c8-c795f15a4b82': 0,
 '00153200-cec7-48a8-9889-c515deb6be06': 0,
 '00153fc3-feb1-4920-ab6c-b507aa2c2fa4': 0,
 '0015538f-6bfc-4317-ac7a-fc2262af4803': 0,
 '00155808-33fb-47cd-9cc9-0926ad18a6d6': 0,
 '00157025-22be-406c-8290-1cc95f900132': 0,
 '00157f35-aaba-4ff7-8a18-b97d3ed12327': 0,
 '00158378-8360-4b24-b407-88d54414e052': 0,
 '00158417-2d96-4a83-9dd6-9da61e1ec513': 0,
 '0015860d-7ca7-4b6e-b2fb-9ef3716e9249': 0,
 '001587ab-b257-4d37-836c-abcc2616e2e9': 0,
 '00158e16-c7e7-42f4-aaad-afd9b9ff4c60': 0,

In [58]:
y

array([0, 0, 0, ..., 0, 0, 0], shape=(1376268,))

In [71]:
session_groups.tolist()

[[[1.0, 0.0, 0.5053023397225167, 0.0]],
 [[1.0, 0.0, 0.7632679460139488, 0.0],
  [1.0, 0.0, 0.7632679460139488, 2.9444389791664403],
  [1.0, 0.0, 0.8245835903159487, 4.143134726391533],
  [1.0, 0.0, 0.8245835903159487, 4.634728988229636],
  [1.0, 0.0, 0.8245835903159487, 4.3694478524670215],
  [1.0, 0.0, 0.9093232845998416, 4.574710978503383],
  [1.0, 0.0, 0.9093232845998416, 3.367295829986474],
  [1.0, 0.0, 0.7877837591512786, 3.9318256327243257],
  [1.0, 0.0, 0.8873973244586164, 3.9512437185814275]],
 [[1.0, 0.0, 0.2530873103778527, 0.0]],
 [[1.0, 0.0, 0.7042206281404793, 0.0],
  [1.0, 0.0, 0.704105670238279, 3.9889840465642745],
  [1.0, 0.0, 0.704105670238279, 3.4011973816621555],
  [1.0, 0.0, 0.7538413315100926, 2.6390573296152584],
  [1.0, 0.0, 0.7538413315100926, 3.367295829986474],
  [1.0, 0.0, 0.7538413315100926, 2.3978952727983707]],
 [[1.0, 0.0, 0.5880030573018032, 0.0],
  [1.0, 0.0, 0.5880030573018032, 4.04305126783455]],
 [[1.0, 0.0, 0.6050791891644948, 0.0],
  [1.0, 0.0, 0.964998067925267, 3.5263605246161616],
  [1.0, 0.0, 0.6764953283853087, 3.6888794541139363],
  [1.0, 0.0, 0.730248727949385, 3.258096538021482],
  [1.0, 0.0, 0.7685268890105574, 2.4849066497880004],
  [1.0, 0.0, 0.9321380106264641, 2.5649493574615367],
  [1.0, 0.0, 0.739611488275979, 2.4849066497880004],
  [1.0, 0.0, 0.739611488275979, 3.4965075614664802],
  [1.0, 0.0, 0.6355378213490703, 3.7612001156935624],
  [1.0, 0.0, 0.8707534912484057, 3.9318256327243257]],
 [[1.0, 0.0, 0.6189880702203396, 0.0]],
 [[1.0, 0.0, 0.38425328278881854, 0.0],
  [1.0, 0.0, 0.6144947343768079, 3.6375861597263857],
  [1.0, 0.0, 0.6844394875640113, 3.6375861597263857],
  [1.0, 0.0, 0.6844394875640113, 2.833213344056216],
  [1.0, 0.0, 0.6945775225748562, 3.044522437723423]],
 [[1.0, 0.0, 0.9999018490728251, 0.0],
  [1.0, 0.0, 0.9999018490728251, 3.8918202981106265]],
 [[1.0, 0.0, 0.6355150805709938, 0.0]],
 [[1.0, 0.0, 0.734973157277929, 0.0]],
 [[1.0, 0.0, 0.7805115721412841, 0.0],
  [1.0, 0.0, 0.7544006113879652, 6.3561076606958915],
  [1.0, 0.0, 0.7544006113879652, 7.052721049232323],
  [1.0, 0.0, 0.7805115721412841, 6.432940092739179],
  [1.0, 0.0, 0.7805115721412841, 4.477336814478207],
  [0.0, 1.0, 0.7805115721412841, 3.5263605246161616]],
 [[1.0, 0.0, 0.7351494015242929, 0.0]],
 [[1.0, 0.0, 0.4954886734935914, 0.0]],
 [[1.0, 0.0, 0.2775479998848275, 0.0]],
 [[1.0, 0.0, 0.6534482483266056, 0.0],
  [0.0, 1.0, 0.6534482483266056, 2.833213344056216]],
 [[1.0, 0.0, 0.4013785978457397, 0.0]],
 [[1.0, 0.0, 0.1971659792908643, 0.0],
  [1.0, 0.0, 0.1971659792908643, 3.295836866004329],
  [1.0, 0.0, 0.14929293102912397, 3.5553480614894135],
  [1.0, 0.0, 0.25296443555279235, 2.4849066497880004]],
 [[1.0, 0.0, 0.7163628300755809, 0.0],
  [1.0, 0.0, 0.7163628300755809, 4.330733340286331]],
 [[1.0, 0.0, 0.8431353798942379, 0.0],
  [1.0, 0.0, 0.7791307351989349, 3.091042453358316],
  [1.0, 0.0, 0.7792106238489904, 3.6635616461296463],
  [1.0, 0.0, 0.5558407390483738, 4.897839799950911],
  [1.0, 0.0, 0.5558407390483738, 3.4965075614664802],
  [1.0, 0.0, 0.50814920191578, 4.990432586778736],
  [1.0, 0.0, 0.50814920191578, 2.6390573296152584]],
 [[1.0, 0.0, 0.8252934149993612, 0.0],
  [1.0, 0.0, 0.8252934149993612, 4.127134385045092]],
 [[1.0, 0.0, 0.6138305100761353, 0.0],
  [1.0, 0.0, 0.6138305100761353, 5.313205979041787]],
 [[1.0, 0.0, 0.6620667443699623, 0.0],
  [1.0, 0.0, 0.6842907658637395, 2.4849066497880004],
  [1.0, 0.0, 0.6842907658637395, 3.9512437185814275]],
 [[1.0, 0.0, 0.6781057895505539, 0.0],
  [0.0, 1.0, 0.6781057895505539, 3.6375861597263857],
  [1.0, 0.0, 0.6781057895505539, 4.912654885736052],
  [0.0, 1.0, 0.6781057895505539, 3.1780538303479458],
  [1.0, 0.0, 0.6781057895505539, 4.859812404361672]],
 [[1.0, 0.0, 0.3467212619864336, 0.0]],
 [[1.0, 0.0, 0.688652919582564, 0.0],
  [1.0, 0.0, 0.6886117278594885, 12.720117083351498],
  [1.0, 0.0, 0.6842588759604783, 13.762239519656209]],
 [[1.0, 0.0, 0.6314606811946372, 0.0],
  [1.0, 0.0, 0.6314606811946372, 1.6094379124341003]],
 [[1.0, 0.0, 0.432717983590041, 0.0],
  [1.0, 0.0, 0.9099401154945737, 3.8501476017100584],
  [1.0, 0.0, 0.7729078758539868, 5.220355825078324],
  [1.0, 0.0, 0.7303551629966424, 4.330733340286331],
  [1.0, 0.0, 0.638455088140015, 3.912023005428146]],
 [[1.0, 0.0, 0.5849476878004356, 0.0]],
 [[1.0, 0.0, 0.5372011084052426, 0.0]],
 [[1.0, 0.0, 0.39688448370958707, 0.0],
  [0.0, 1.0, 0.39688448370958707, 2.0794415416798357]],
 [[1.0, 0.0, 0.4578028220510252, 0.0]],
 [[1.0, 0.0, 0.5228578215412772, 0.0],
  [1.0, 0.0, 0.5111259259339951, 3.044522437723423],
  [1.0, 0.0, 0.5446137891542058, 3.258096538021482],
  [1.0, 0.0, 0.5445402852673041, 3.332204510175204],
  [1.0, 0.0, 0.5467284640681876, 3.1780538303479458],
  [1.0, 0.0, 0.531030320796522, 4.23410650459726],
  [1.0, 0.0, 0.5462064725333051, 2.70805020110221]],
 [[1.0, 0.0, 0.2712385006325302, 0.0],
  [0.0, 1.0, 0.2712385006325302, 2.833213344056216],
  [0.0, 1.0, 0.2712385006325302, 2.0794415416798357],
  [0.0, 1.0, 0.2712385006325302, 1.791759469228055],
  [0.0, 1.0, 0.2712385006325302, 1.6094379124341003]],
 [[1.0, 0.0, 0.4496562180471366, 0.0]],
 [[1.0, 0.0, 0.6549106889031702, 0.0],
  [1.0, 0.0, 0.6549106889031702, 4.90527477843843]],
 [[1.0, 0.0, 0.3564884992388748, 0.0]],
 [[1.0, 0.0, 0.6841684809939703, 0.0],
  [1.0, 0.0, 0.4107297821458251, 3.4657359027997265],
  [1.0, 0.0, 0.43544624723722536, 3.8918202981106265],
  [1.0, 0.0, 0.41757023060163956, 4.394449154672439],
  [1.0, 0.0, 0.43459742670164436, 3.8918202981106265],
  [1.0, 0.0, 0.41757023060163956, 3.367295829986474],
  [1.0, 0.0, 0.4222352264331848, 3.912023005428146]],
 [[1.0, 0.0, 0.6392172596119936, 0.0]],
 [[1.0, 0.0, 0.6973307008656519, 0.0]],
 [[1.0, 0.0, 0.5589075839638702, 0.0],
  [1.0, 0.0, 0.5589075839638702, 5.537334267018537],
  [1.0, 0.0, 0.5589075839638702, 3.7376696182833684],
  [1.0, 0.0, 0.5589075839638702, 3.6109179126442243]],
 [[1.0, 0.0, 0.4075766560473073, 0.0],
  [1.0, 0.0, 0.4075766560473073, 4.07753744390572],
  [1.0, 0.0, 0.5007868373114688, 4.248495242049359]],
 [[1.0, 0.0, 0.7791493800416947, 0.0],
  [1.0, 0.0, 0.8151757111486073, 3.4339872044851463],
  [1.0, 0.0, 0.7791493800416947, 3.332204510175204]],
 [[1.0, 0.0, 0.7922739514767453, 0.0]],
 [[1.0, 0.0, 0.3728285873179552, 0.0],
  [1.0, 0.0, 0.4024174332427879, 7.1180162044653335]],
 [[1.0, 0.0, 0.7466966123958729, 0.0],
  [1.0, 0.0, 0.7466966123958729, 4.875197323201151]],
 [[1.0, 0.0, 0.6518893435946539, 0.0],
  [1.0, 0.0, 0.6518893435946539, 3.091042453358316]],
 [[1.0, 0.0, 0.748632747889093, 0.0]],
 [[1.0, 0.0, 0.6248056752673473, 0.0],
  [1.0, 0.0, 0.6351887148789932, 4.653960350157523],
  [1.0, 0.0, 0.6351887148789932, 4.77912349311153],
  [1.0, 0.0, 0.6248056752673473, 3.7612001156935624],
  [1.0, 0.0, 0.6248056752673473, 4.663439094112067],
  [1.0, 0.0, 0.5947357234242193, 3.4657359027997265],
  [1.0, 0.0, 0.5947357234242193, 4.30406509320417],
  [1.0, 0.0, 0.6248056752673473, 3.9318256327243257],
  [1.0, 0.0, 0.5743961805876279, 3.970291913552122],
  [1.0, 0.0, 0.5743961805876279, 4.23410650459726],
  [1.0, 0.0, 0.6248056752673473, 3.5553480614894135],
  [1.0, 0.0, 0.6142913802956395, 4.634728988229636],
  [1.0, 0.0, 0.6142913802956395, 4.7535901911063645],
  [1.0, 0.0, 0.6142913802956395, 4.90527477843843],
  [1.0, 0.0, 0.4954886734935914, 4.605170185988092],
  [1.0, 0.0, 0.4954886734935914, 3.912023005428146],
  [1.0, 0.0, 0.505888145251981, 3.828641396489095],
  [1.0, 0.0, 0.505888145251981, 3.9512437185814275],
  [1.0, 0.0, 0.508130033547236, 4.532599493153256],
  [1.0, 0.0, 0.508130033547236, 3.970291913552122],
  [1.0, 0.0, 0.508130033547236, 5.153291594497779],
  [1.0, 0.0, 0.7201023101035574, 5.627621113690637],
  [1.0, 0.0, 0.7201023101035574, 3.912023005428146],
  [1.0, 0.0, 0.24782948525808954, 5.910796644040527],
  [1.0, 0.0, 0.24782948525808954, 3.4965075614664802]],
 [[1.0, 0.0, 0.7261849120397668, 0.0],
  [1.0, 0.0, 0.7261849120397668, 3.091042453358316],
  [1.0, 0.0, 0.7372215755207635, 1.791759469228055],
  [1.0, 0.0, 0.7372215755207635, 2.3978952727983707],
  [1.0, 0.0, 0.7372215755207635, 2.0794415416798357]],
 [[1.0, 0.0, 0.6182249584433979, 0.0]],
 [[1.0, 0.0, 0.5975730494785332, 0.0],
  [1.0, 0.0, 0.6868808519756385, 4.564348191467836],
  [1.0, 0.0, 0.6868808519756385, 5.278114659230517],
  [1.0, 0.0, 0.6953788981314054, 5.187385805840755],
  [1.0, 0.0, 0.6868808519756385, 4.343805421853684],
  [1.0, 0.0, 0.6894076261375575, 4.204692619390966],
  [1.0, 0.0, 0.6269928364986216, 3.367295829986474],
  [1.0, 0.0, 0.6250186011646024, 4.941642422609304]],
 [[1.0, 0.0, 0.7491374033338718, 0.0],
  [1.0, 0.0, 0.7491374033338718, 3.6375861597263857],
  [1.0, 0.0, 0.6649050453656783, 2.0794415416798357],
  [1.0, 0.0, 0.7757409272863358, 2.995732273553991],
  [1.0, 0.0, 0.4075766560473073, 3.332204510175204],
  [1.0, 0.0, 0.9963827396851779, 4.174387269895637],
  [1.0, 0.0, 0.7556104219263521, 3.871201010907891],
  [1.0, 0.0, 0.7485562237359543, 2.1972245773362196]],
 [[1.0, 0.0, 0.7922182666987985, 0.0]],
 [[1.0, 0.0, 0.657137093348353, 0.0],
  [0.0, 1.0, 0.657137093348353, 3.295836866004329]],
 [[1.0, 0.0, 0.4086885051005932, 0.0]],
 [[1.0, 0.0, 0.37148692771367553, 0.0],
  [1.0, 0.0, 0.42216354143659873, 4.248495242049359],
  [1.0, 0.0, 0.36603918894797893, 4.219507705176107],
  [1.0, 0.0, 0.4002898065955287, 4.02535169073515],
  [1.0, 0.0, 0.4267815999908573, 3.4965075614664802]],
 [[1.0, 0.0, 0.4146477782952007, 0.0]],
 [[1.0, 0.0, 0.6842907658637395, 0.0],
  [1.0, 0.0, 0.6842907658637395, 5.572154032177765]],
 [[1.0, 0.0, 0.4899559680522657, 0.0]],
 [[1.0, 0.0, 0.7935149288367005, 0.0]],
 [[1.0, 0.0, 0.5407081955128737, 0.0],
  [1.0, 0.0, 0.5407081955128737, 2.8903717578961645],
  [0.0, 1.0, 0.5407081955128737, 3.7376696182833684]],
 [[1.0, 0.0, 0.4482106535557189, 0.0]],
 [[1.0, 0.0, 0.6276526850400322, 0.0],
  [1.0, 0.0, 0.7307080884891829, 3.258096538021482],
  [1.0, 0.0, 0.6463770179039927, 3.4339872044851463],
  [1.0, 0.0, 0.5927524273317349, 3.4657359027997265],
  [1.0, 0.0, 0.5812049393048515, 4.248495242049359],
  [1.0, 0.0, 0.7057473044648533, 4.812184355372417]],
 [[1.0, 0.0, 0.6026449278399033, 0.0],
  [1.0, 0.0, 0.6394973842111048, 3.332204510175204],
  [1.0, 0.0, 0.6409040778018813, 2.8903717578961645],
  [1.0, 0.0, 0.6409040778018813, 3.332204510175204],
  [1.0, 0.0, 0.6409040778018813, 2.9444389791664403],
  [1.0, 0.0, 0.6412898591903444, 2.4849066497880004],
  [1.0, 0.0, 0.6412898591903444, 3.258096538021482],
  [1.0, 0.0, 0.6524265873292202, 2.6390573296152584],
  [1.0, 0.0, 0.6598369401794631, 3.2188758248682006],
  [1.0, 0.0, 0.677565484086544, 2.995732273553991],
  [1.0, 0.0, 0.6812602660079108, 3.295836866004329],
  [1.0, 0.0, 0.7052007496454316, 4.976733742420574],
  [1.0, 0.0, 0.7242242562734906, 3.6109179126442243],
  [1.0, 0.0, 0.7242242562734906, 3.1354942159291497],
  [1.0, 0.0, 0.7237625804520702, 2.3978952727983707],
  [1.0, 0.0, 0.7243473727647853, 2.8903717578961645],
  [1.0, 0.0, 0.728980383350037, 2.833213344056216],
  [1.0, 0.0, 0.7324816864778722, 2.995732273553991],
  [1.0, 0.0, 0.7324816864778722, 3.2188758248682006],
  [1.0, 0.0, 0.7469123431674148, 3.295836866004329],
  [1.0, 0.0, 0.9388503346995996, 3.9512437185814275],
  [1.0, 0.0, 0.6254189893077482, 3.5263605246161616],
  [1.0, 0.0, 0.6412898591903444, 3.295836866004329],
  [1.0, 0.0, 0.6412898591903444, 2.70805020110221],
  [1.0, 0.0, 0.6959073064673321, 3.8066624897703196],
  [1.0, 0.0, 0.7065450034002673, 3.6635616461296463],
  [1.0, 0.0, 0.7065450034002673, 4.859812404361672],
  [1.0, 0.0, 0.7452621798138124, 2.5649493574615367]],
 [[1.0, 0.0, 0.7201023101035574, 0.0],
  [1.0, 0.0, 0.6972194989448063, 2.4849066497880004],
  [1.0, 0.0, 0.7201023101035574, 3.258096538021482],
  [1.0, 0.0, 0.7252731592617582, 5.0106352940962555],
  [1.0, 0.0, 0.7252731592617582, 2.9444389791664403],
  [1.0, 0.0, 0.6972194989448063, 4.343805421853684],
  [1.0, 0.0, 0.7459626170798391, 4.8283137373023015],
  [1.0, 0.0, 0.7568597998303953, 3.8918202981106265],
  [1.0, 0.0, 0.7607544683980596, 2.833213344056216],
  [1.0, 0.0, 0.7664363161841468, 3.4657359027997265],
  [1.0, 0.0, 0.6972194989448063, 5.389071729816501],
  [1.0, 0.0, 0.6972194989448063, 4.543294782270004],
  [1.0, 0.0, 0.7201023101035574, 2.1972245773362196],
  [1.0, 0.0, 0.7201023101035574, 4.564348191467836],
  [1.0, 0.0, 0.6972194989448063, 2.6390573296152584],
  [1.0, 0.0, 0.6972194989448063, 2.1972245773362196],
  [1.0, 0.0, 0.7252731592617582, 5.402677381872279],
  [1.0, 0.0, 0.8099686647925641, 3.7376696182833684],
  [1.0, 0.0, 0.8099686647925641, 3.4965075614664802],
  [1.0, 0.0, 0.7544261241005531, 4.736198448394496],
  [1.0, 0.0, 0.7832684637488668, 3.9889840465642745],
  [1.0, 0.0, 0.7333432381319194, 4.110873864173311],
  [1.0, 0.0, 0.6972194989448063, 3.2188758248682006],
  [1.0, 0.0, 0.7664363161841468, 2.9444389791664403],
  [1.0, 0.0, 0.7791493800416947, 2.302585092994046],
  [1.0, 0.0, 0.8121431150363546, 3.4657359027997265],
  [1.0, 0.0, 0.794499698313619, 4.127134385045092],
  [1.0, 0.0, 0.7940559922056278, 3.367295829986474],
  [1.0, 0.0, 0.7929018660739302, 2.833213344056216],
  [1.0, 0.0, 0.7929018660739302, 4.51085950651685],
  [1.0, 0.0, 0.7201023101035574, 2.302585092994046],
  [1.0, 0.0, 0.7832684637488668, 1.9459101490553132],
  [1.0, 0.0, 0.7607544683980596, 2.4849066497880004],
  [1.0, 0.0, 0.7832684637488668, 2.5649493574615367],
  [1.0, 0.0, 0.7929018660739302, 2.3978952727983707],
  [1.0, 0.0, 0.7929018660739302, 3.091042453358316],
  [1.0, 0.0, 0.7832684637488668, 2.3978952727983707],
  [1.0, 0.0, 0.7832684637488668, 5.293304824724492],
  [1.0, 0.0, 0.7791493800416947, 5.886104031450156],
  [1.0, 0.0, 0.7207436249321022, 4.553876891600541],
  [1.0, 0.0, 0.7668127031990639, 6.042632833682381],
  [1.0, 0.0, 0.7668127031990639, 3.6888794541139363],
  [1.0, 0.0, 0.7383339201013361, 2.6390573296152584],
  [1.0, 0.0, 0.7995018550103155, 4.382026634673881],
  [1.0, 0.0, 0.7995018550103155, 2.6390573296152584],
  [1.0, 0.0, 0.7282839397285353, 4.04305126783455],
  [1.0, 0.0, 0.7471815308792719, 5.484796933490655],
  [1.0, 0.0, 0.7183718195525604, 2.8903717578961645],
  [1.0, 0.0, 0.7791493800416947, 2.995732273553991],
  [1.0, 0.0, 0.7485562237359543, 3.332204510175204],
  [1.0, 0.0, 0.748632747889093, 3.044522437723423],
  [1.0, 0.0, 0.7475910288032601, 3.091042453358316],
  [1.0, 0.0, 0.7538541405220275, 3.044522437723423],
  [1.0, 0.0, 0.7721168170838376, 3.044522437723423],
  [1.0, 0.0, 0.7137720294305917, 4.07753744390572],
  [1.0, 0.0, 0.7995018550103155, 4.624972813284271],
  [1.0, 0.0, 0.7461287012437071, 4.0943445622221],
  [1.0, 0.0, 0.7282839397285353, 3.6888794541139363],
  [1.0, 0.0, 0.8000907820951064, 4.90527477843843],
  [1.0, 0.0, 0.8042017392725782, 4.276666119016055],
  [1.0, 0.0, 0.7922182666987985, 3.784189633918261],
  [1.0, 0.0, 0.7721168170838376, 2.995732273553991],
  [1.0, 0.0, 0.7410742290444525, 2.772588722239781],
  [1.0, 0.0, 0.7668127031990639, 4.23410650459726],
  [1.0, 0.0, 0.7721168170838376, 4.127134385045092],
  [1.0, 0.0, 0.7721168170838376, 3.332204510175204],
  [1.0, 0.0, 0.7668127031990639, 2.5649493574615367],
  [1.0, 0.0, 0.7668127031990639, 2.3978952727983707],
  [1.0, 0.0, 0.7668127031990639, 4.574710978503383],
  [1.0, 0.0, 0.7721168170838376, 2.9444389791664403],
  [1.0, 0.0, 0.5592514939600313, 6.580639137284949],
  [1.0, 0.0, 0.6313982024731215, 5.0369526024136295],
  [1.0, 0.0, 0.5519535609396735, 5.19295685089021],
  [1.0, 0.0, 0.5658918520379906, 3.828641396489095],
  [1.0, 0.0, 0.505888145251981, 4.3694478524670215],
  [1.0, 0.0, 0.6275000752996006, 4.110873864173311],
  [1.0, 0.0, 0.5197579252511607, 5.170483995038151],
  [1.0, 0.0, 0.5179852101079536, 5.117993812416755],
  [1.0, 0.0, 0.5407535506273544, 4.605170185988092],
  [1.0, 0.0, 0.5407535506273544, 3.044522437723423]],
 [[1.0, 0.0, 0.8349969746402234, 0.0],
  [1.0, 0.0, 0.8349969746402234, 2.3978952727983707],
  [1.0, 0.0, 0.7865476961525779, 4.51085950651685],
  [1.0, 0.0, 0.9034960047804751, 3.9318256327243257],
  [1.0, 0.0, 0.7983140522035326, 3.5553480614894135],
  [1.0, 0.0, 0.8349969746402234, 2.3978952727983707],
  [1.0, 0.0, 0.8349969746402234, 2.5649493574615367],
  [1.0, 0.0, 0.8349969746402234, 2.302585092994046],
  [1.0, 0.0, 0.8349969746402234, 0.6931471805599453]],
 [[1.0, 0.0, 0.7351494015242929, 0.0],
  [1.0, 0.0, 0.7148269877026477, 3.258096538021482],
  [1.0, 0.0, 0.6331755107223491, 3.6635616461296463],
  [1.0, 0.0, 0.709238985522472, 3.6888794541139363],
  [1.0, 0.0, 0.7201964481456178, 4.219507705176107],
  [1.0, 0.0, 0.7201964481456178, 2.772588722239781],
  [1.0, 0.0, 0.7438436060439853, 3.5263605246161616],
  [1.0, 0.0, 0.7438436060439853, 3.4965075614664802]],
 [[1.0, 0.0, 0.46199714687779314, 0.0]],
 [[1.0, 0.0, 0.5056931542964048, 0.0],
  [1.0, 0.0, 0.5720935649801027, 4.04305126783455]],
 [[1.0, 0.0, 0.697093683887939, 0.0]],
 [[1.0, 0.0, 0.3853357871031423, 0.0],
  [1.0, 0.0, 0.6098676491256582, 3.4339872044851463],
  [1.0, 0.0, 0.4231637417537749, 3.912023005428146],
  [1.0, 0.0, 0.5522736208748388, 4.23410650459726],
  [1.0, 0.0, 0.44512147694089343, 4.189654742026425],
  [1.0, 0.0, 0.5522736208748388, 4.553876891600541],
  [1.0, 0.0, 0.5896327416369864, 3.4011973816621555],
  [1.0, 0.0, 0.5522736208748388, 3.6635616461296463],
  [1.0, 0.0, 0.44512147694089343, 1.791759469228055]],
 [[1.0, 0.0, 0.23790851732827004, 0.0],
  [1.0, 0.0, 0.31817631446831773, 3.091042453358316],
  [1.0, 0.0, 0.24008596803608387, 2.70805020110221],
  [1.0, 0.0, 0.18257555699273806, 2.772588722239781],
  [1.0, 0.0, 0.22223178426802634, 2.6390573296152584],
  [1.0, 0.0, 0.17925164018962683, 3.8066624897703196],
  [1.0, 0.0, 0.17606065365151471, 3.9889840465642745],
  [1.0, 0.0, 0.17606065365151471, 3.7376696182833684],
  [1.0, 0.0, 0.24744610871912012, 5.247024072160486],
  [1.0, 0.0, 0.191706637051381, 3.828641396489095],
  [1.0, 0.0, 0.6122231385701494, 3.828641396489095],
  [1.0, 0.0, 0.11195300339590075, 3.912023005428146],
  [1.0, 0.0, 0.08512118660004647, 3.1780538303479458],
  [1.0, 0.0, 0.21448267270966473, 3.044522437723423],
  [1.0, 0.0, 0.15188381181498462, 3.4657359027997265],
  [1.0, 0.0, 0.15188381181498462, 3.4657359027997265],
  [1.0, 0.0, 0.17606065365151471, 2.5649493574615367],
  [1.0, 0.0, 0.15188381181498462, 5.777652323222656],
  [1.0, 0.0, 0.15188381181498462, 2.3978952727983707],
  [1.0, 0.0, 0.17606065365151471, 2.4849066497880004],
  [1.0, 0.0, 0.17606065365151471, 2.1972245773362196]],
 [[1.0, 0.0, 0.6395930852685611, 0.0],
  [1.0, 0.0, 0.7124104397601688, 3.871201010907891],
  [1.0, 0.0, 0.7124104397601688, 4.867534450455582],
  [1.0, 0.0, 0.7124104397601688, 3.58351893845611]],
 [[1.0, 0.0, 0.7330566544615762, 0.0]],
 [[1.0, 0.0, 0.8436508438904234, 0.0]],
 [[1.0, 0.0, 0.49225613821443825, 0.0]],
 [[1.0, 0.0, 0.8626315300421401, 0.0],
  [1.0, 0.0, 0.7560586096662518, 3.871201010907891],
  [1.0, 0.0, 0.7560586096662518, 2.9444389791664403]],
 [[1.0, 0.0, 0.5351853309344263, 0.0],
  [1.0, 0.0, 0.5293981536199067, 3.4011973816621555],
  [1.0, 0.0, 0.26303498560627225, 6.035481432524756]],
 [[1.0, 0.0, 0.9993811173984339, 0.0]],
 [[1.0, 0.0, 0.5069363381881183, 0.0]],
 [[1.0, 0.0, 0.5893571624009989, 0.0],
  [0.0, 1.0, 0.5893571624009989, 5.1647859739235145]],
 [[1.0, 0.0, 0.46407364697901576, 0.0],
  [1.0, 0.0, 0.7473528630115461, 4.927253685157205],
  [1.0, 0.0, 0.7473528630115461, 3.8066624897703196]],
 [[1.0, 0.0, 0.8347129443744447, 0.0]],
 [[1.0, 0.0, 0.5054392513861483, 0.0],
  [1.0, 0.0, 0.5054392513861483, 3.2188758248682006],
  [0.0, 1.0, 0.5054392513861483, 5.3981627015177525],
  [1.0, 0.0, 0.5054392513861483, 4.543294782270004],
  [0.0, 1.0, 0.5054392513861483, 3.258096538021482],
  [1.0, 0.0, 0.5054392513861483, 5.996452088619021],
  [1.0, 0.0, 0.5054392513861483, 2.1972245773362196],
  [1.0, 0.0, 0.5054392513861483, 1.9459101490553132],
  [1.0, 0.0, 0.5343801612804356, 6.493753839851686],

## Fix karr diya ki har_matrix 15*4 ka hi hoga neeche waaale code se!!

In [73]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
MAX_STEPS = 15
X = pad_sequences(session_groups.tolist(), maxlen=MAX_STEPS, padding='post', truncating='pre', dtype='float32')

ModuleNotFoundError: No module named 'tensorflow'

In [78]:
seq_df.head(2)

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session,category_code_filled,brand_filled,hour,is_view,is_cart,time_gap_seconds,log_time_gap,log_price,scaled_price
0,2019-11-02 13:29:04+00:00,view,12300059,2053013556311359947,construction.tools.drill,bosch,69.17,513196170,00000510-834a-498a-9bed-561a90c5125e,construction.tools.drill,bosch,13,1,0,0.0,0.0,4.250921,0.505302
1,2019-11-01 19:06:53+00:00,view,1002544,2053013555631882655,electronics.smartphone,apple,458.25,514001239,000009c4-a1dd-4764-87d9-24f3d7e43c4f,electronics.smartphone,apple,19,1,0,0.0,0.0,6.129595,0.763268

In [81]:
p = seq_df.groupby('user_session')['event_type'].agg(
    view_count=lambda x: (x == 'view').sum()
)

# Result check karne ke liye:
print(p.describe())

KeyboardInterrupt:

In [82]:
# Har session mein total kitne events (views + carts) hue?
session_lengths = seq_df.groupby('user_session')['event_type'].count()

# Ab check karte hain ki 15 theek hai ya nahi:
print(session_lengths.describe(percentiles=[0.50, 0.75, 0.90, 0.95, 0.99]))

count    1.376268e+06
mean     4.807747e+00
std      7.672263e+00
min      1.000000e+00
50%      2.000000e+00
75%      5.000000e+00
90%      1.100000e+01
95%      1.700000e+01
99%      3.600000e+01
max      9.150000e+02
Name: event_type, dtype: float64

In [83]:
session_lengths

user_session
00000510-834a-498a-9bed-561a90c5125e     1
000009c4-a1dd-4764-87d9-24f3d7e43c4f     9
0000189b-6d2d-45bc-a65c-3a9d94e330a4     1
000029a6-1986-4a71-8139-53669c1adaba     6
00003dca-5a5a-4af2-86ef-9851ceb02a2b     2
                                        ..
ffffb94a-cea4-429d-ba4a-7e47a6f28171    13
ffffb9ea-87d1-4f3d-b107-91b1bb087d36     5
ffffcdf8-f820-4b22-acee-d8c425b624fc     1
ffffecf5-59d6-42b2-ac84-143e24b06557     1
fffffbbc-3c59-46fb-9165-fa46f027e332     1
Name: event_type, Length: 1376268, dtype: int64